import { useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, ArrowRight, Heart, MapPin, PawPrint, Plus, Search, Trash2 } from "lucide-react";
import { adoptions } from "../data.js";
import { useApp } from "../store.jsx";
import { btn, btn2, card, input } from "../ui.js";
import { Badge, Button, EmptyState, Modal } from "../components/ui.jsx";
import Media from "../components/Media.jsx";
import PhotoUpload from "../components/PhotoUpload.jsx";

const animalTypes = ["Dog", "Cat", "Bird", "Other"];
const listingFields = { name: "", type: "Dog", breed: "", age: "", gender: "Female", city: "", health: "Healthy", description: "", photo: "" };
const getPhoto = (animal) => animal.photo || animal.images?.[0] || animal.image;

export function AdoptionHub() {
  const { adoptionListings } = useApp();
  const [filters, setFilters] = useState({ q: "", city: "", type: "", breed: "", age: "", gender: "" });
  const animals = [...adoptionListings, ...adoptions.map((animal) => ({ ...animal, status: "Available", description: animal.description || `${animal.name} is looking for a caring home.`, ownerId: null }))].filter((animal) => animal.status !== "Adopted");
  const update = (key) => (event) => setFilters((current) => ({ ...current, [key]: event.target.value }));
  const list = useMemo(() => animals.filter((animal) => (!filters.q || `${animal.name} ${animal.breed} ${animal.city}`.toLowerCase().includes(filters.q.toLowerCase())) && (!filters.type || animal.type === filters.type) && (!filters.city || animal.city === filters.city) && (!filters.breed || animal.breed.toLowerCase().includes(filters.breed.toLowerCase())) && (!filters.gender || animal.gender === filters.gender) && (!filters.age || Number(animal.age) <= Number(filters.age))), [adoptionListings, filters]);
  return <div><header className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-wider text-primary-700">Make room for love</p><h1 className="mt-2 text-3xl font-extrabold">Meet your new best friend</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-ink-500">Find a good match close to home or share an animal looking for a family.</p></div><div className="flex flex-wrap gap-2"><Link to="/adoption/my-listings" className={btn2}>My listings</Link><Link to="/adoption/new" className={btn}><Plus size={16} /> Publish listing</Link></div></header>
    <div className="mb-6 grid gap-3 rounded-xl border border-stone-200 bg-white p-4 sm:grid-cols-2 lg:grid-cols-6"><label className="relative sm:col-span-2"><span className="sr-only">Search adoption listings</span><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-ink-500" /><input aria-label="Search adoption listings" className={`${input} pl-9`} placeholder="Search animals" value={filters.q} onChange={update("q")} /></label><label><span className="sr-only">Animal type</span><select aria-label="Animal type" className={input} value={filters.type} onChange={update("type")}><option value="">All types</option>{animalTypes.map((type) => <option key={type}>{type}</option>)}</select></label><label><span className="sr-only">City</span><select aria-label="Adoption city" className={input} value={filters.city} onChange={update("city")}><option value="">All cities</option>{[...new Set(animals.map((animal) => animal.city))].filter(Boolean).sort().map((city) => <option key={city}>{city}</option>)}</select></label><label><span className="sr-only">Breed</span><input aria-label="Breed" className={input} placeholder="Breed" value={filters.breed} onChange={update("breed")} /></label><label><span className="sr-only">Maximum age</span><input aria-label="Maximum age" className={input} type="number" min="0" placeholder="Max age" value={filters.age} onChange={update("age")} /></label><label><span className="sr-only">Gender</span><select aria-label="Gender" className={input} value={filters.gender} onChange={update("gender")}><option value="">Any gender</option><option>Female</option><option>Male</option></select></label></div>
    {list.length ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{list.map((animal) => <article key={animal.id} className={`${card} flex h-full flex-col overflow-hidden p-0`}><Link to={`/adoption/${animal.id}`} className="relative block h-52 bg-primary-50"><Media src={getPhoto(animal)} alt={`${animal.name}, ${animal.breed || animal.type}`} className="size-full object-cover" /><Badge className="absolute left-3 top-3" variant="success">{animal.status || "Available"}</Badge></Link><div className="flex flex-1 flex-col p-4"><h2 className="text-lg font-extrabold"><Link to={`/adoption/${animal.id}`}>{animal.name}</Link></h2><p className="mt-1 text-sm text-ink-500">{animal.breed || "Mixed breed"} · {animal.age} years · {animal.gender}</p><p className="mt-3 flex items-center gap-1 text-xs text-ink-500"><MapPin size={14} /> {animal.city}</p><p className="mt-3 line-clamp-2 text-sm leading-6 text-ink-500">{animal.description}</p><Link to={`/adoption/${animal.id}`} className={`${btn2} mt-auto w-full`}><Heart size={15} /> View adoption details</Link></div></article>)}</div> : <EmptyState title="No animals match these filters" description="Try changing your search or filters." icon={PawPrint} action={<button className={btn2} onClick={() => setFilters({ q: "", city: "", type: "", breed: "", age: "", gender: "" })}>Clear filters</button>} />}</div>;
}

export function AdoptionDetails() {
  const { id } = useParams(); const { adoptionListings, user, showToast } = useApp();
  const [requested, setRequested] = useState(false);
  const animal = adoptionListings.find((item) => String(item.id) === id) || adoptions.find((item) => String(item.id) === id);
  if (!animal) return <div className="mx-auto max-w-xl py-8"><EmptyState title="Listing not found" description="This adoption listing may have been removed." icon={PawPrint} action={<Link to="/adoption" className={btn}>Browse adoption</Link>} /></div>;
  return <div><Link to="/adoption" className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-primary-700"><ArrowLeft size={16} /> Adoption</Link><div className="grid items-start gap-6 lg:grid-cols-2"><Media src={getPhoto(animal)} alt={`${animal.name}, ${animal.breed || animal.type}`} className="aspect-[4/3] w-full rounded-2xl object-cover" /><section className={`${card}`}><Badge variant="success">{animal.status || "Available"}</Badge><h1 className="mt-3 text-3xl font-extrabold">{animal.name}</h1><p className="mt-2 text-sm text-ink-500">{animal.type} · {animal.breed || "Mixed breed"}</p><div className="mt-5 grid grid-cols-2 gap-4 border-y border-stone-100 py-4 text-sm"><p><span className="block text-xs text-ink-500">Age</span><strong>{animal.age} years</strong></p><p><span className="block text-xs text-ink-500">Gender</span><strong>{animal.gender}</strong></p><p><span className="block text-xs text-ink-500">City</span><strong>{animal.city}</strong></p><p><span className="block text-xs text-ink-500">Health</span><strong>{animal.health || "Healthy"}</strong></p></div><p className="mt-5 text-sm leading-7 text-ink-700">{animal.description || `${animal.name} is looking for a safe, loving home.`}</p><button type="button" disabled={(animal.status || "Available") !== "Available" || requested} onClick={() => { setRequested(true); showToast(`Your interest in ${animal.name} has been recorded for this demo.`); }} className={`${btn} mt-6 w-full`}><Heart size={16} /> {requested ? "Request sent" : "Ask about adoption"}</button>{!user && <p className="mt-3 text-xs text-ink-500">Sign in to keep track of your adoption interest.</p>}</section></div></div>;
}

function ListingForm({ initial = listingFields, onSubmit, submitLabel }) {
  const [form, setForm] = useState(initial);
  const set = (key) => (event) => setForm((current) => ({ ...current, [key]: event.target.value }));
  return <form className={`${card} space-y-4`} onSubmit={(event) => { event.preventDefault(); onSubmit({ ...form, age: Number(form.age) }); }}><div><h1 className="text-2xl font-extrabold">{submitLabel === "Publish listing" ? "Publish an adoption listing" : "Edit listing"}</h1><p className="mt-2 text-sm text-ink-500">Share the details that will help a pet find a good home.</p></div><label className="block text-xs font-bold">Photo<div className="mt-2"><PhotoUpload label="Adoption animal photo" value={form.photo || ""} onChange={(photo) => setForm((current) => ({ ...current, photo }))} /></div></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-xs font-bold">Animal name<input required className={`${input} mt-2`} value={form.name} onChange={set("name")} /></label><label className="block text-xs font-bold">Type<select className={`${input} mt-2`} value={form.type} onChange={set("type")}>{animalTypes.map((type) => <option key={type}>{type}</option>)}</select></label><label className="block text-xs font-bold">Breed<input className={`${input} mt-2`} value={form.breed} onChange={set("breed")} /></label><label className="block text-xs font-bold">Age in years<input required type="number" min="0" className={`${input} mt-2`} value={form.age} onChange={set("age")} /></label><label className="block text-xs font-bold">Gender<select className={`${input} mt-2`} value={form.gender} onChange={set("gender")}><option>Female</option><option>Male</option></select></label><label className="block text-xs font-bold">City<input required className={`${input} mt-2`} value={form.city} onChange={set("city")} /></label><label className="block text-xs font-bold sm:col-span-2">Health information<input className={`${input} mt-2`} value={form.health} onChange={set("health")} /></label><label className="block text-xs font-bold sm:col-span-2">Description<textarea required rows="4" className={`${input} mt-2`} value={form.description} onChange={set("description")} /></label></div><Button>{submitLabel}</Button></form>;
}

export function AdoptionNew() {
  const { user, createAdoptionListing, showToast } = useApp(); const navigate = useNavigate();
  if (!user) return <div className="mx-auto max-w-xl py-8"><EmptyState title="Please log in to publish a listing" description="Sign in to manage your adoption posts." icon={PawPrint} action={<Link to="/login" state={{ from: "/adoption/new" }} className={btn}>Log in</Link>} /></div>;
  return <div className="mx-auto max-w-3xl"><Link to="/adoption" className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-primary-700"><ArrowLeft size={16} /> Adoption</Link><ListingForm submitLabel="Publish listing" onSubmit={async (listing) => { await createAdoptionListing(listing); showToast("Adoption listing published."); navigate("/adoption/my-listings"); }} /></div>;
}

export function MyAdoptionListings() {
  const { user, adoptionListings, updateAdoptionListing, deleteAdoptionListing, showToast } = useApp();
  const [editing, setEditing] = useState(null); const [deleting, setDeleting] = useState(null);
  const mine = adoptionListings.filter((listing) => listing.ownerId === user?.email);
  if (!user) return <div className="mx-auto max-w-xl py-8"><EmptyState title="Please log in to manage listings" icon={PawPrint} action={<Link to="/login" state={{ from: "/adoption/my-listings" }} className={btn}>Log in</Link>} /></div>;
  return <div><header className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-wider text-primary-700">Your posts</p><h1 className="mt-2 text-3xl font-extrabold">My adoption listings</h1></div><Link to="/adoption/new" className={btn}><Plus size={16} /> Publish listing</Link></header>{mine.length ? <div className="grid gap-4 md:grid-cols-2">{mine.map((listing) => <article key={listing.id} className={`${card} flex gap-4`}><Media src={getPhoto(listing)} alt={listing.name} className="size-24 shrink-0 rounded-xl object-cover" /><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><h2 className="truncate font-extrabold">{listing.name}</h2><Badge variant={listing.status === "Available" ? "success" : "neutral"}>{listing.status}</Badge></div><p className="mt-1 text-xs text-ink-500">{listing.type} · {listing.city}</p><div className="mt-3 flex flex-wrap gap-2"><button className={btn2} onClick={() => setEditing(listing)}>Edit</button><select aria-label={`Change status for ${listing.name}`} className={`${input} min-h-9 w-auto py-1`} value={listing.status} onChange={async (event) => { await updateAdoptionListing(listing.id, { status: event.target.value }); showToast("Listing status updated."); }}><option>Available</option><option>Adopted</option></select><button aria-label={`Delete ${listing.name}`} onClick={() => setDeleting(listing)} className="grid size-9 place-items-center rounded-lg text-danger-600 hover:bg-red-50"><Trash2 size={15} /></button></div></div></article>)}</div> : <EmptyState title="No adoption listings yet" description="Publish an animal listing and manage it here." icon={PawPrint} action={<Link className={btn} to="/adoption/new">Publish listing</Link>} />}
    <Modal open={Boolean(editing)} onClose={() => setEditing(null)} title="Edit adoption listing">{editing && <ListingForm key={editing.id} initial={{ ...listingFields, ...editing, photo: getPhoto(editing) }} submitLabel="Save changes" onSubmit={async (changes) => { await updateAdoptionListing(editing.id, changes); setEditing(null); showToast("Listing updated."); }} />}</Modal>
    <Modal open={Boolean(deleting)} onClose={() => setDeleting(null)} title="Delete this listing?"><p className="text-sm text-ink-500">This adoption listing will be removed.</p><div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={() => setDeleting(null)}>Keep listing</Button><Button variant="danger" onClick={async () => { await deleteAdoptionListing(deleting.id); setDeleting(null); showToast("Listing deleted."); }}>Delete listing</Button></div></Modal>
  </div>;
}
