import { useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { ArrowLeft, Eye, EyeOff, Heart, LockKeyhole, LogOut, Mail, MapPin, Phone, Save, UserRound } from "lucide-react";
import { useApp } from "../store.jsx";
import { btn, btn2, card, input } from "../ui.js";
import Media from "../components/Media.jsx";
import PhotoUpload from "../components/PhotoUpload.jsx";
import { Button, Modal } from "../components/ui.jsx";
import PetAvatar from "../components/PetAvatar.jsx";

function displayNameFromEmail(email) {
  const prefix = email.split("@")[0].replace(/\d+$/, "").replace(/[._]+/g, " ").replace(/\s+/g, " ").trim();
  return prefix.split(" ").filter(Boolean).map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1).toLowerCase()}`).join(" ") || "Pet parent";
}

function AuthShell({ title, eyebrow, children }) {
  return <div className="mx-auto grid min-h-[570px] max-w-5xl overflow-hidden rounded-[28px] border border-stone-200 bg-white shadow-[0_18px_60px_-38px_rgba(23,49,47,0.4)] md:grid-cols-[0.9fr_1.1fr]">
    <aside className="relative isolate hidden min-h-full flex-col justify-between overflow-hidden bg-[#17312f] p-9 text-white md:flex"><Media src="https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=1000&q=80" alt="A golden dog outdoors" className="absolute inset-0 -z-10 h-full w-full object-cover opacity-45" /><div className="absolute inset-0 -z-10 bg-gradient-to-t from-[#17312f] via-[#17312f]/45 to-[#17312f]/15" /><Link to="/" className="flex items-center gap-2 font-extrabold"><span className="grid size-9 place-items-center rounded-xl bg-white/15"><Heart size={19} /></span> PetCare</Link><div><p className="text-xs font-extrabold uppercase tracking-wider text-accent-400">A little more peace of mind</p><p className="mt-3 max-w-sm text-3xl font-extrabold leading-tight">Good care feels better when it’s all together.</p><p className="mt-4 max-w-sm text-sm leading-6 text-white/70">Appointments, records, and everyday essentials for the pets you love.</p></div><span className="text-xs text-white/60">Care for every stage, close to home.</span></aside>
    <section className="flex items-center p-5 sm:p-8 md:p-10"><div className="mx-auto w-full max-w-md"><Link to="/" className="mb-8 inline-flex items-center gap-2 text-xs font-bold text-ink-500 hover:text-primary-700 md:hidden"><ArrowLeft size={15} /> PetCare home</Link><p className="text-xs font-extrabold uppercase tracking-wider text-primary-700">{eyebrow}</p><h1 className="mt-2 text-2xl font-extrabold sm:text-3xl">{title}</h1>{children}</div></section>
  </div>;
}

function PasswordInput({ id, label, value, onChange, required = true }) {
  const [visible, setVisible] = useState(false);
  return <label htmlFor={id} className="block text-xs font-bold">{label}<span className="relative mt-2 block"><LockKeyhole size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-ink-500" /><input id={id} required={required} type={visible ? "text" : "password"} className={`${input} pr-12 pl-10`} placeholder={label} value={value} onChange={onChange} /><button type="button" aria-label={visible ? "Hide password" : "Show password"} onClick={() => setVisible(!visible)} className="absolute right-3 top-1/2 grid size-8 -translate-y-1/2 place-items-center rounded-lg text-ink-500 hover:bg-stone-100">{visible ? <EyeOff size={17} /> : <Eye size={17} />}</button></span></label>;
}

export function Login() {
  const { user, saveUser } = useApp(); const nav = useNavigate(); const location = useLocation(); const [f, setF] = useState({ email: "", password: "" }); const [saving, setSaving] = useState(false);
  return <AuthShell title="Welcome back" eyebrow="Your pet's care, together"><form className="mt-7 space-y-5" onSubmit={async (e) => { e.preventDefault(); setSaving(true); try { await saveUser({ name: user?.name?.trim() || displayNameFromEmail(f.email), email: f.email, phone: user?.phone || "", city: user?.city || "", avatar: user?.avatar || "" }); nav(location.state?.from || "/"); } finally { setSaving(false); } }}><label htmlFor="login-email" className="block text-xs font-bold">Email address<span className="relative mt-2 block"><Mail size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-ink-500" /><input id="login-email" required type="email" className={`${input} pl-10`} placeholder="you@example.com" value={f.email} onChange={(e) => setF({ ...f, email: e.target.value })} /></span></label><PasswordInput id="login-password" label="Password" value={f.password} onChange={(e) => setF({ ...f, password: e.target.value })} /><div className="flex justify-end"><Link className="text-xs font-bold text-primary-700 hover:underline" to="/forgot-password">Forgot password?</Link></div><Button disabled={saving} className="w-full">{saving ? "Signing in..." : "Log in"}</Button></form><p className="mt-6 text-center text-sm text-ink-500">New to PetCare? <Link className="font-bold text-primary-700" to="/register">Create an account</Link></p></AuthShell>;
}
export function Register() {
  const { saveUser } = useApp(); const nav = useNavigate(); const [err, setErr] = useState(""); const [saving, setSaving] = useState(false);
  const [f, setF] = useState({ name: "", email: "", phone: "", city: "", password: "", confirm: "", terms: false });
  const set = (k) => (e) => setF({ ...f, [k]: e.target.type === "checkbox" ? e.target.checked : e.target.value });
  const submit = async (e) => { e.preventDefault(); if (f.password.length < 6) return setErr("Password must be at least 6 characters."); if (f.password !== f.confirm) return setErr("Passwords do not match."); setSaving(true); try { await saveUser({ name: f.name, email: f.email, phone: f.phone, city: f.city }); nav("/"); } finally { setSaving(false); } };
  return <AuthShell title="Create your account" eyebrow="A better day for every pet"><form className="mt-6 space-y-4" onSubmit={submit}><label className="block text-xs font-bold">Full name<input required className={`${input} mt-2`} placeholder="Your name" value={f.name} onChange={set("name")} /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-xs font-bold">Email<input required type="email" className={`${input} mt-2`} placeholder="you@example.com" value={f.email} onChange={set("email")} /></label><label className="block text-xs font-bold">Phone<input required type="tel" className={`${input} mt-2`} placeholder="Phone number" value={f.phone} onChange={set("phone")} /></label></div><label className="block text-xs font-bold">City<input required className={`${input} mt-2`} placeholder="Your city" value={f.city} onChange={set("city")} /></label><div className="grid gap-4 sm:grid-cols-2"><PasswordInput id="register-password" label="Password" value={f.password} onChange={set("password")} /><PasswordInput id="register-confirm" label="Confirm password" value={f.confirm} onChange={set("confirm")} /></div><label className="flex items-start gap-2 text-xs leading-5 text-ink-700"><input required type="checkbox" className="mt-1 accent-primary-600" checked={f.terms} onChange={set("terms")} /> I agree to the terms</label>{err && <p role="alert" className="text-sm font-semibold text-danger-600">{err}</p>}<Button disabled={saving} className="w-full">{saving ? "Creating account..." : "Create account"}</Button></form><p className="mt-5 text-center text-sm text-ink-500">Already registered? <Link className="font-bold text-primary-700" to="/login">Log in</Link></p></AuthShell>;
}
export function Forgot() {
  const [step, setStep] = useState(1);
  return <AuthShell title="Reset password" eyebrow="Account help">{step === 1 && <form className="mt-6 space-y-4" onSubmit={(e) => { e.preventDefault(); setStep(2); }}><p className="text-sm leading-6 text-ink-500">Enter the email address associated with your account.</p><label className="block text-xs font-bold">Email address<input required type="email" className={`${input} mt-2`} placeholder="you@example.com" /></label><button className={`${btn} w-full`}>Send reset link</button></form>}{step === 2 && <form className="mt-6 space-y-4" onSubmit={(e) => { e.preventDefault(); setStep(3); }}><p className="text-sm leading-6 text-ink-500">Link sent (demo). Choose a new password to continue.</p><PasswordInput id="new-password" label="New password" value={undefined} onChange={() => {}} /><button className={`${btn} w-full`}>Save password</button></form>}{step === 3 && <div className="mt-6 rounded-xl bg-primary-50 p-4"><p className="flex items-center gap-2 font-bold text-primary-700"><Heart size={17} /> Password updated.</p><Link className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-primary-700" to="/login">Back to log in <ArrowLeft size={15} /></Link></div>}</AuthShell>;
}
export function Profile() {
  const { user, setUser, saveUser, clearDemoData, showToast } = useApp(); const nav = useNavigate(); const [f, setF] = useState(user || {}); const [saved, setSaved] = useState(false); const [clearOpen, setClearOpen] = useState(false); const [passwords, setPasswords] = useState({ current: "", next: "", confirm: "" }); const [passwordError, setPasswordError] = useState("");
  if (!user) return <div className={`${card} mx-auto max-w-lg py-14 text-center`}><UserRound size={30} className="mx-auto text-primary-600" /><h1 className="mt-4 text-2xl font-extrabold">Your profile is waiting</h1><p className="mt-2 text-sm text-ink-500">Log in to manage your account details.</p><Link className={`${btn} mt-5`} to="/login">Log in</Link></div>;
  const updateField = (key) => (event) => setF((current) => ({ ...current, [key]: event.target.value }));
  const savePassword = (event) => { event.preventDefault(); setPasswordError(""); if (passwords.current.length < 1) return setPasswordError("Enter your current password."); if (passwords.next.length < 6) return setPasswordError("New password must be at least 6 characters."); if (passwords.next !== passwords.confirm) return setPasswordError("New passwords do not match."); setPasswords({ current: "", next: "", confirm: "" }); showToast("Password updated for this demo."); };
  return <AuthShell title="Your profile" eyebrow="Account settings"><div className="mt-6 space-y-7">
    <section aria-label="Profile photo" className="flex flex-col gap-4 sm:flex-row sm:items-center"><span className="grid size-24 shrink-0 place-items-center overflow-hidden rounded-full border border-stone-200 bg-primary-100 text-3xl font-semibold text-primary-800">{f.avatar || user.avatar ? <img src={f.avatar || user.avatar} alt="Profile" className="size-full object-cover" /> : (f.name || user.name || "U").trim().slice(0, 1).toUpperCase()}</span><div><p className="text-sm font-bold">Profile photo</p><div className="mt-2"><PhotoUpload value={f.avatar || ""} showPreview={false} square label="Profile photo" onChange={(avatar) => setF((current) => ({ ...current, avatar }))} /></div></div></section>
    <form className="space-y-4" onSubmit={async (e) => { e.preventDefault(); await saveUser({ ...user, ...f }); setSaved(true); showToast("Profile saved."); }}>
      {[ ["name", "Full name", UserRound], ["email", "Email", Mail], ["phone", "Phone", Phone], ["city", "City", MapPin] ].map(([key, label, Icon]) => <label key={key} className="block text-xs font-bold">{label}<span className="relative mt-2 block"><Icon size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-ink-500" /><input required={key === "name" || key === "email"} type={key === "email" ? "email" : "text"} aria-label={label} className={`${input} pl-10`} placeholder={label} value={f[key] || ""} onChange={updateField(key)} /></span></label>)}
      <label className="block text-xs font-bold">Language<select className={`${input} mt-2`}><option>English</option><option>العربية</option></select></label><Button type="submit" className="w-full"><Save size={16} /> Save changes</Button>{saved && <p role="status" className="text-center text-sm font-semibold text-primary-700">Changes saved</p>}</form>
    <section className="border-t border-stone-100 pt-6"><h2 className="text-lg font-extrabold">Change password</h2><p className="mt-1 text-sm text-ink-500">Demo only. Passwords are not stored.</p><form className="mt-4 space-y-3" onSubmit={savePassword}>{[["current", "Current password"], ["next", "New password"], ["confirm", "Confirm new password"]].map(([key, label]) => <label key={key} className="block text-xs font-bold">{label}<input aria-label={label} type="password" className={`${input} mt-2`} value={passwords[key]} onChange={(event) => setPasswords((current) => ({ ...current, [key]: event.target.value }))} /></label>)}{passwordError && <p role="alert" className="text-xs font-semibold text-danger-600">{passwordError}</p>}<Button type="submit" variant="secondary" className="w-full"><LockKeyhole size={16} /> Update password</Button></form></section>
    <div className="border-t border-stone-100 pt-5"><button type="button" className={`${btn2} w-full`} onClick={() => { setUser(null); nav("/"); }}><LogOut size={16} /> Log out</button><button type="button" className="mt-3 w-full rounded-xl px-4 py-3 text-sm font-semibold text-danger-600 hover:bg-red-50" onClick={() => setClearOpen(true)}>Clear demo data</button></div>
  </div><Modal open={clearOpen} onClose={() => setClearOpen(false)} title="Clear demo data?"><p className="text-sm leading-6 text-ink-500">This removes the demo user, pets, bookings, and cart from this browser.</p><div className="mt-6 flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => setClearOpen(false)}>Keep data</Button><Button type="button" variant="danger" onClick={async () => { await clearDemoData(); setClearOpen(false); showToast("Demo data cleared."); nav("/"); }}>Clear demo data</Button></div></Modal></AuthShell>;
}
