import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, CalendarDays, ChevronLeft, ChevronRight, Clock3, Pencil, Plus, Trash2 } from "lucide-react";
import { useApp } from "../store.jsx";
import { btn, btn2, card, input } from "../ui.js";
import { Badge, Button, EmptyState, Modal } from "../components/ui.jsx";

const eventTypes = ["Vaccination", "Medication", "Veterinary appointment", "Grooming", "Pet sitting", "Custom reminder"];
const typeStyles = { Vaccination: "success", Medication: "warning", "Veterinary appointment": "danger", Grooming: "neutral", "Pet sitting": "neutral", "Custom reminder": "warning" };
const today = new Date();
const dateInput = (date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;

export default function Calendar() {
  const { user, pets, bookings, calendarEvents, createCalendarEvent, updateCalendarEvent, deleteCalendarEvent, showToast } = useApp();
  const [petFilter, setPetFilter] = useState("all");
  const [month, setMonth] = useState(new Date(today.getFullYear(), today.getMonth(), 1));
  const [modalOpen, setModalOpen] = useState(false);
  const [editing, setEditing] = useState(null);
  const [deleting, setDeleting] = useState(null);
  const [form, setForm] = useState({ petId: pets[0]?.id || "", type: "Custom reminder", title: "", date: dateInput(today), time: "09:00", notes: "" });
  const customEvents = calendarEvents.filter((event) => petFilter === "all" || String(event.petId) === petFilter);
  const autoEvents = [
    ...pets.flatMap((pet) => (pet.vaccines || []).filter((vaccine) => vaccine.next).map((vaccine, index) => ({ id: `vaccine-${pet.id}-${index}`, petId: pet.id, petName: pet.name, title: vaccine.name, type: "Vaccination", date: vaccine.next, time: "09:00", notes: "Next vaccination date", readonly: true }))),
    ...bookings.filter((booking) => booking.status === "Upcoming").map((booking) => ({ id: `booking-${booking.id}`, petId: booking.pet?.id, petName: booking.pet?.name, title: booking.provider?.name || "Appointment", type: booking.provider?.type === "grooming" ? "Grooming" : booking.provider?.type === "sitting" ? "Pet sitting" : "Veterinary appointment", date: booking.date, time: booking.time, notes: booking.notes || "Upcoming booking", readonly: true })),
  ].filter((event) => petFilter === "all" || String(event.petId) === petFilter);
  const events = [...customEvents, ...autoEvents].sort((a, b) => `${a.date} ${a.time || ""}`.localeCompare(`${b.date} ${b.time || ""}`));
  const monthEvents = events.filter((event) => event.date?.startsWith(`${month.getFullYear()}-${String(month.getMonth() + 1).padStart(2, "0")}`));
  const days = useMemo(() => {
    const first = new Date(month.getFullYear(), month.getMonth(), 1);
    const offset = (first.getDay() + 6) % 7;
    const count = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate();
    return [...Array(offset).fill(null), ...Array.from({ length: count }, (_, index) => index + 1)];
  }, [month]);
  const openCreate = () => { setEditing(null); setForm({ petId: pets[0]?.id || "", type: "Custom reminder", title: "", date: dateInput(today), time: "09:00", notes: "" }); setModalOpen(true); };
  const openEdit = (event) => { setEditing(event); setForm({ petId: event.petId || pets[0]?.id || "", type: event.type, title: event.title, date: event.date, time: event.time || "09:00", notes: event.notes || "" }); setModalOpen(true); };
  const submit = async (event) => { event.preventDefault(); const pet = pets.find((item) => String(item.id) === String(form.petId)); const record = { ...form, petId: pet?.id, petName: pet?.name }; if (editing) await updateCalendarEvent(editing.id, record); else await createCalendarEvent(record); setModalOpen(false); showToast(editing ? "Reminder updated." : "Reminder added."); };
  const confirmDelete = async () => { await deleteCalendarEvent(deleting.id); setDeleting(null); showToast("Reminder deleted."); };
  if (!user) return <div className="mx-auto max-w-xl py-8"><EmptyState title="Please log in to view your calendar" description="Your pet reminders and appointments are saved with your account." icon={CalendarDays} action={<Link to="/login" state={{ from: "/calendar" }} className={btn}>Log in</Link>} /></div>;
  return <div><header className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-wider text-primary-700">Care at a glance</p><h1 className="mt-2 text-3xl font-extrabold">Pet calendar</h1><p className="mt-2 text-sm text-ink-500">Appointments, health reminders, and important dates.</p></div><button type="button" className={btn} onClick={openCreate}><Plus size={17} /> Add event / reminder</button></header>
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><label className="text-xs font-bold">Pet<select aria-label="Filter calendar by pet" className={`${input} mt-1 min-w-44`} value={petFilter} onChange={(event) => setPetFilter(event.target.value)}><option value="all">All pets</option>{pets.map((pet) => <option key={pet.id} value={pet.id}>{pet.name}</option>)}</select></label><div className="flex items-center gap-2"><button type="button" aria-label="Previous month" className={`${btn2} size-10 min-h-10 p-0`} onClick={() => setMonth((value) => new Date(value.getFullYear(), value.getMonth() - 1, 1))}><ChevronLeft size={17} /></button><h2 className="min-w-36 text-center text-base font-extrabold">{month.toLocaleDateString(undefined, { month: "long", year: "numeric" })}</h2><button type="button" aria-label="Next month" className={`${btn2} size-10 min-h-10 p-0`} onClick={() => setMonth((value) => new Date(value.getFullYear(), value.getMonth() + 1, 1))}><ChevronRight size={17} /></button></div></div>
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_360px]"><section className={`${card} p-3 sm:p-5`} aria-label="Monthly calendar"><div className="grid grid-cols-7 gap-1 text-center text-[11px] font-bold text-ink-500">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day) => <span key={day} className="py-2">{day}</span>)}{days.map((day, index) => { const date = day ? dateInput(new Date(month.getFullYear(), month.getMonth(), day)) : ""; const count = events.filter((event) => event.date === date).length; const isToday = date === dateInput(today); return <div key={`${date}-${index}`} className={`min-h-14 rounded-lg border p-1 text-sm sm:min-h-20 sm:p-2 ${day ? "border-stone-100 bg-white" : "border-transparent"} ${isToday ? "ring-2 ring-primary-500" : ""}`}><span className="font-semibold">{day || ""}</span>{count > 0 && <span className="mx-auto mt-1 grid size-5 place-items-center rounded-full bg-primary-600 text-[10px] font-bold text-white">{count}</span>}</div>; })}</div></section>
      <section><h2 className="mb-3 text-lg font-extrabold">This month</h2>{monthEvents.length ? <div className="space-y-3">{monthEvents.map((event) => <article key={event.id} className={`${card} p-4`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Badge variant={typeStyles[event.type] || "neutral"}>{event.type}</Badge>{event.petName && <span className="text-xs text-ink-500">{event.petName}</span>}</div><h3 className="mt-2 font-extrabold">{event.title}</h3><p className="mt-1 flex items-center gap-1 text-xs text-ink-500"><CalendarDays size={13} /> {event.date} <Clock3 size={13} className="ms-2" /> {event.time || "All day"}</p>{event.notes && <p className="mt-2 text-xs leading-5 text-ink-500">{event.notes}</p>}</div>{!event.readonly && <div className="flex gap-1"><button type="button" aria-label={`Edit ${event.title}`} onClick={() => openEdit(event)} className="grid size-8 place-items-center rounded-lg text-ink-500 hover:bg-primary-50"><Pencil size={14} /></button><button type="button" aria-label={`Delete ${event.title}`} onClick={() => setDeleting(event)} className="grid size-8 place-items-center rounded-lg text-ink-500 hover:bg-red-50"><Trash2 size={14} /></button></div>}</div></article>)}</div> : <div className={`${card} py-10 text-center`}><CalendarDays size={26} className="mx-auto text-primary-600" /><h3 className="mt-3 font-extrabold">No events this month</h3><p className="mt-1 text-sm text-ink-500">Add a reminder or check another month.</p><button className={`${btn2} mt-4`} onClick={openCreate}><Plus size={15} /> Add reminder</button></div>}</section></div>
    <Modal open={modalOpen} onClose={() => setModalOpen(false)} title={editing ? "Edit event" : "Add event or reminder"}><form onSubmit={submit} className="space-y-4"><label className="block text-xs font-bold">Pet<select required className={`${input} mt-2`} value={form.petId} onChange={(event) => setForm((value) => ({ ...value, petId: event.target.value }))}>{pets.map((pet) => <option key={pet.id} value={pet.id}>{pet.name}</option>)}</select></label><label className="block text-xs font-bold">Event type<select className={`${input} mt-2`} value={form.type} onChange={(event) => setForm((value) => ({ ...value, type: event.target.value }))}>{eventTypes.map((type) => <option key={type}>{type}</option>)}</select></label><label className="block text-xs font-bold">Title<input required className={`${input} mt-2`} value={form.title} onChange={(event) => setForm((value) => ({ ...value, title: event.target.value }))} /></label><div className="grid gap-3 sm:grid-cols-2"><label className="block text-xs font-bold">Date<input required type="date" className={`${input} mt-2`} value={form.date} onChange={(event) => setForm((value) => ({ ...value, date: event.target.value }))} /></label><label className="block text-xs font-bold">Time<input type="time" className={`${input} mt-2`} value={form.time} onChange={(event) => setForm((value) => ({ ...value, time: event.target.value }))} /></label></div><label className="block text-xs font-bold">Notes<textarea rows="3" className={`${input} mt-2`} value={form.notes} onChange={(event) => setForm((value) => ({ ...value, notes: event.target.value }))} /></label><div className="flex justify-end"><Button>{editing ? "Save changes" : "Add reminder"}</Button></div></form></Modal>
    <Modal open={Boolean(deleting)} onClose={() => setDeleting(null)} title="Delete this reminder?"><p className="text-sm text-ink-500">This event will be removed from your calendar.</p><div className="mt-5 flex justify-end gap-2"><Button variant="secondary" onClick={() => setDeleting(null)}>Keep event</Button><Button variant="danger" onClick={confirmDelete}>Delete event</Button></div></Modal>
  </div>;
}
