import { useRef, useState } from "react";
import { Activity, Bot, Camera, Clock3, MapPin, Phone, ShieldAlert, UploadCloud } from "lucide-react";
import { card } from "../ui.js";
import { ChatConversation } from "../components/ChatWidget.jsx";
const clinics = [["Happy Paws Clinic (24h)", "Cairo", "01000000010"], ["Alexandria Animal Hospital (24h)", "Alexandria", "01000000011"], ["Giza Vet Pharmacy", "Giza", "01000000012"]];
export function Emergency() {
  return <div><section className="relative isolate overflow-hidden rounded-[28px] bg-[#702f2a] px-6 py-10 text-white sm:px-10 sm:py-14"><div className="absolute -right-10 -top-14 -z-10 size-72 rounded-full border-[40px] border-white/5" /><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-extrabold uppercase tracking-wider"><ShieldAlert size={15} /> Urgent pet care</span><h1 className="mt-5 max-w-2xl text-3xl font-extrabold sm:text-4xl">When every minute matters, reach out.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-white/75">Call a nearby clinic for urgent advice. This directory is demo data; contact the clinic directly to confirm availability.</p><a href="tel:01000000010" className="mt-6 inline-flex min-h-12 items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-extrabold text-[#702f2a] hover:bg-red-50"><Phone size={18} /> Call nearest clinic</a></section>
    <section className="mt-10"><div className="mb-5"><p className="text-xs font-extrabold uppercase tracking-wider text-danger-600">Get help now</p><h2 className="mt-2 text-2xl font-extrabold">Nearby emergency contacts</h2></div><div className="grid gap-4">{clinics.map(([name, city, telephone], index) => <article key={name} className={`${card} flex flex-wrap items-center justify-between gap-4`}><div className="flex items-center gap-4"><span className={`grid size-12 place-items-center rounded-xl ${index === 0 ? "bg-red-50 text-danger-600" : "bg-primary-50 text-primary-700"}`}><Activity size={22} /></span><div><h3 className="font-extrabold">{name}</h3><p className="mt-1 flex items-center gap-2 text-sm text-ink-500"><MapPin size={14} /> {city}<span className="text-stone-300">·</span><Clock3 size={14} /> 24 hours</p></div></div><a href={`tel:${telephone}`} className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-danger-600 px-4 py-2 text-sm font-bold text-white hover:bg-red-700"><Phone size={16} /> Call clinic</a></article>)}</div></section>
    <section className="mt-10"><div className="mb-5"><p className="text-xs font-extrabold uppercase tracking-wider text-primary-700">Clinic locations</p><h2 className="mt-2 text-2xl font-extrabold">Find care near you</h2></div><div className="relative isolate flex min-h-64 items-center justify-center overflow-hidden rounded-2xl border border-stone-200 bg-[#e8f0e9] p-6 text-center"><div className="absolute inset-0 -z-10 opacity-50" style={{ backgroundImage: "linear-gradient(30deg, transparent 47%, #c8d9ce 48%, #c8d9ce 50%, transparent 51%), linear-gradient(120deg, transparent 47%, #d6e1d8 48%, #d6e1d8 50%, transparent 51%)", backgroundSize: "76px 76px" }} /><span className="grid size-14 place-items-center rounded-full bg-primary-700 text-white shadow-lg"><MapPin size={25} /></span><div className="absolute left-[24%] top-[25%] grid size-9 place-items-center rounded-full bg-white text-danger-600 shadow"><MapPin size={17} /></div><div className="absolute right-[22%] bottom-[24%] grid size-9 place-items-center rounded-full bg-white text-primary-700 shadow"><MapPin size={17} /></div><div className="absolute bottom-4 rounded-lg bg-white/90 px-3 py-2 text-xs font-semibold text-ink-500">Map preview · clinic locations are illustrative</div></div></section></div>;
}
export function AI() {
  const [img, setImg] = useState(null); const [dragging, setDragging] = useState(false); const fileInput = useRef(null);
  const addImage = (file) => { if (file?.type.startsWith("image/")) setImg(URL.createObjectURL(file)); };
  return <div><div className="mb-7"><p className="text-xs font-extrabold uppercase tracking-wider text-primary-700">PetCare assistant</p><h1 className="mt-2 text-3xl font-extrabold">A little help, right here</h1><p className="mt-2 text-sm text-ink-500">Explore the care demo or try a breed photo preview.</p></div><div className="grid items-start gap-6 lg:grid-cols-[1.1fr_0.9fr]">
    <section className={`${card} overflow-hidden !p-0`}><ChatConversation embedded prompts={["How often should I brush my cat?", "What should I pack for a vet visit?"]} /></section>
    <section className={`${card} p-5 sm:p-6`}><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-accent-50 text-accent-500"><Camera size={20} /></span><div><h2 className="font-extrabold">Breed recognition</h2><p className="text-xs text-ink-500">Photo preview demo</p></div></div><button type="button" onClick={() => fileInput.current?.click()} onDragOver={(event) => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={(event) => { event.preventDefault(); setDragging(false); addImage(event.dataTransfer.files[0]); }} className={`mt-5 flex min-h-52 w-full flex-col items-center justify-center rounded-2xl border-2 border-dashed p-6 text-center transition ${dragging ? "border-primary-500 bg-primary-50" : "border-stone-300 bg-stone-50 hover:border-primary-500 hover:bg-primary-50/50"}`}><UploadCloud size={28} className="text-primary-600" /><b className="mt-3 text-sm">Drop a photo here or browse</b><span className="mt-1 text-xs text-ink-500">JPG or PNG image</span><input ref={fileInput} className="sr-only" type="file" accept="image/*" onChange={(event) => addImage(event.target.files[0])} /></button>{img && <><img src={img} alt="Selected pet for breed recognition preview" className="mt-4 max-h-60 w-full rounded-xl object-cover" /><p className="mt-3 rounded-xl bg-accent-50 p-3 text-sm leading-5 text-ink-700">This is a demo preview. Connect a recognition model to identify breeds.</p></>}</section></div></div>;
}
