import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowRight, ArrowUpRight, CalendarDays, Clock3, Heart, MapPin, PawPrint, Plus, Search, ShieldCheck, ShoppingBag, Star, Stethoscope, Scissors, House, Sparkles } from "lucide-react";
import { useApp } from "../store.jsx";
import { adoptions, products, providers } from "../data.js";
import Media from "../components/Media.jsx";
import { btn, card, input } from "../ui.js";

const services = [["/services/vet", "Veterinary", "Health, checkups & more", Stethoscope], ["/services/grooming", "Grooming", "Freshen up and feel good", Scissors], ["/services/sitting", "Pet sitting", "A trusted friend for your pet", House]];

export default function Home() {
  const { pets, bookings } = useApp();
  const navigate = useNavigate();
  const [service, setService] = useState("vet");
  const [city, setCity] = useState("");
  const next = bookings.find((booking) => booking.status === "Upcoming");
  const search = (event) => { event.preventDefault(); navigate(`/services/${service}${city ? `?city=${encodeURIComponent(city)}` : ""}`); };

  return <div className="space-y-16 md:space-y-20">
    <section className="relative isolate overflow-hidden rounded-[28px] bg-[#163c36] text-white shadow-xl shadow-primary-900/10">
      <div className="absolute inset-0 -z-10"><Media src="https://images.unsplash.com/photo-1551717743-49959800b1f6?auto=format&fit=crop&w=1600&q=80" alt="A happy dog spending time with its owner" className="h-full w-full object-cover opacity-35" /><div className="absolute inset-0 bg-gradient-to-r from-[#163c36] via-[#163c36]/85 to-[#163c36]/25" /></div>
      <div className="grid min-h-[470px] items-center gap-8 px-6 py-12 sm:px-10 md:px-14 lg:grid-cols-[1.2fr_0.8fr] lg:px-16">
        <div className="max-w-2xl"><span className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-xs font-bold"><Sparkles size={14} className="text-accent-400" /> Better days start with good care</span><h1 className="mt-6 max-w-xl text-4xl font-extrabold leading-[1.1] sm:text-5xl lg:text-[58px]">For every little <span className="text-accent-400">paw</span> in your life.</h1><p className="mt-5 max-w-lg text-base leading-7 text-white/75 sm:text-lg">Book trusted local care, keep every record close, and find the things that make tails wag.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/services" className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-accent-400 px-5 py-3 text-sm font-extrabold text-ink-900 hover:bg-amber-300">Explore services <ArrowRight size={17} /></Link><Link to="/pets" className="inline-flex min-h-12 items-center gap-2 rounded-xl border border-white/30 px-5 py-3 text-sm font-bold text-white hover:bg-white/15"><PawPrint size={17} /> Meet my pets</Link></div></div>
        <form onSubmit={search} className="rounded-2xl border border-white/20 bg-white p-5 text-ink-900 shadow-2xl sm:p-6"><p className="text-xs font-bold uppercase tracking-wider text-primary-700">Find the right care</p><h2 className="mb-5 mt-1 text-xl font-extrabold">Where can we help?</h2><label htmlFor="home-service" className="mb-2 block text-xs font-bold">Service</label><select id="home-service" className={`${input} mb-4`} value={service} onChange={(event) => setService(event.target.value)}><option value="vet">Veterinary</option><option value="grooming">Grooming</option><option value="sitting">Pet sitting</option></select><label htmlFor="home-city" className="mb-2 block text-xs font-bold">City</label><div className="relative"><MapPin size={17} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-ink-500" /><select id="home-city" className={`${input} mb-5 pl-10`} value={city} onChange={(event) => setCity(event.target.value)}><option value="">All cities</option><option>Cairo</option><option>Giza</option><option>Alexandria</option></select></div><button className={`${btn} w-full`}><Search size={17} /> Search providers</button></form>
      </div>
    </section>

    <section><div className="mb-6 flex items-end justify-between"><div><p className="text-xs font-extrabold uppercase tracking-wider text-primary-700">Care made simple</p><h2 className="mt-2 text-2xl font-extrabold sm:text-3xl">A little help goes a long way</h2></div><Link to="/services" className="text-sm font-bold text-primary-700">All services <ArrowRight size={16} className="ml-1 inline" /></Link></div><div className="grid gap-4 sm:grid-cols-3">{services.map(([to, title, detail, Icon], index) => <Link key={to} to={to} className={`${card} group flex items-center gap-4 hover:-translate-y-1 hover:shadow-lg`}><span className={`grid size-14 shrink-0 place-items-center rounded-2xl ${["bg-primary-50 text-primary-700", "bg-accent-50 text-accent-500", "bg-sky-50 text-sky-700"][index]}`}><Icon size={25} strokeWidth={1.8} /></span><span className="min-w-0 flex-1"><b className="block">{title}</b><span className="mt-1 block text-sm text-ink-500">{detail}</span></span><ArrowUpRight size={18} className="text-ink-500 group-hover:text-primary-700" /></Link>)}</div><Link to="/emergency" className="mt-4 flex items-center justify-between gap-4 rounded-2xl border border-red-100 bg-red-50 px-5 py-4 text-danger-600"><span><b className="block text-sm">Need urgent help?</b><span className="mt-1 block text-xs text-red-800/70">Find nearby emergency clinics, available around the clock.</span></span><span className="shrink-0 text-sm font-bold">Emergency care <ArrowRight size={15} className="ml-1 inline" /></span></Link></section>

    <section className="grid items-center gap-8 rounded-[28px] bg-[#eef5f1] p-6 sm:p-9 lg:grid-cols-[0.85fr_1.15fr] lg:p-12"><div><p className="text-xs font-extrabold uppercase tracking-wider text-primary-700">Easy as 1, 2, 3</p><h2 className="mt-2 text-2xl font-extrabold sm:text-3xl">Good care, without the guesswork.</h2><p className="mt-3 text-sm leading-6 text-ink-500">A few simple steps connect you with the care your pet needs.</p><Link to="/services" className={`${btn} mt-6`}>Get started <ArrowRight size={16} /></Link></div><div className="grid gap-3 sm:grid-cols-3">{[["01", "Choose a service", "Browse trusted local providers."], ["02", "Pick a time", "Find an appointment that works."], ["03", "Enjoy peace of mind", "Keep care details together."]].map(([number, title, text]) => <div key={number} className="rounded-2xl bg-white p-5"><span className="text-sm font-extrabold text-primary-600">{number}</span><h3 className="mt-5 text-sm font-extrabold">{title}</h3><p className="mt-2 text-xs leading-5 text-ink-500">{text}</p></div>)}</div></section>

    <section><div className="mb-6 flex items-end justify-between"><div><p className="text-xs font-extrabold uppercase tracking-wider text-primary-700">Loved nearby</p><h2 className="mt-2 text-2xl font-extrabold sm:text-3xl">Popular care providers</h2></div><Link to="/services" className="text-sm font-bold text-primary-700">See all <ArrowRight size={16} className="ml-1 inline" /></Link></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{providers.slice(0, 3).map((provider) => <Link key={provider.id} to={`/services/${provider.type}/${provider.id}`} className={`${card} group overflow-hidden p-0 hover:-translate-y-1 hover:shadow-lg`}><div className="relative h-48"><Media src={provider.image} alt={provider.name} className="h-full w-full object-cover" /><span className="absolute left-3 top-3 rounded-full bg-white/95 px-3 py-1 text-xs font-bold text-primary-700">{provider.type}</span></div><div className="p-5"><div className="flex justify-between gap-3"><div><h3 className="font-extrabold">{provider.name}</h3><p className="mt-1 flex items-center gap-1 text-sm text-ink-500"><MapPin size={14} /> {provider.city}</p></div><span className="flex items-center gap-1 text-sm font-bold"><Star size={15} fill="currentColor" className="text-accent-500" /> {provider.rating}</span></div><div className="mt-4 flex justify-between border-t border-stone-100 pt-4 text-sm"><span className="text-ink-500">From <b className="text-ink-900">{provider.price} EGP</b></span><span className="font-bold text-primary-700">View <ArrowRight size={15} className="ml-1 inline" /></span></div></div></Link>)}</div></section>

    <section className="grid gap-8 lg:grid-cols-[1.2fr_0.8fr]"><div><div className="mb-6 flex items-end justify-between"><div><p className="text-xs font-extrabold uppercase tracking-wider text-primary-700">The little things</p><h2 className="mt-2 text-2xl font-extrabold">Pet parent favourites</h2></div><Link to="/store" className="text-sm font-bold text-primary-700">Visit store <ArrowRight size={15} className="ml-1 inline" /></Link></div><div className="grid grid-cols-2 gap-4">{products.slice(0, 2).map((product) => <Link to="/store" key={product.id} className={`${card} overflow-hidden p-0`}><Media src={product.image} alt={product.name} className="h-36 w-full object-cover" /><div className="p-4"><p className="text-xs font-semibold text-ink-500">{product.cat}</p><h3 className="mt-1 line-clamp-1 text-sm font-extrabold">{product.name}</h3><p className="mt-2 font-bold text-primary-700">{product.price} EGP</p></div></Link>)}</div></div><div className="relative isolate overflow-hidden rounded-2xl bg-[#f6eee1] p-6 sm:p-8"><Media src={adoptions[0].image} alt={`Pet available for adoption, ${adoptions[0].name}`} className="absolute inset-0 -z-10 h-full w-full object-cover opacity-20" /><div className="absolute inset-0 -z-10 bg-gradient-to-r from-[#f6eee1] via-[#f6eee1]/90 to-[#f6eee1]/30" /><span className="inline-flex size-11 items-center justify-center rounded-xl bg-white text-danger-600"><Heart size={21} /></span><p className="mt-5 text-xs font-extrabold uppercase tracking-wider text-primary-700">A home for every heart</p><h2 className="mt-2 max-w-xs text-2xl font-extrabold">Your new best friend might be waiting.</h2><p className="mt-3 max-w-xs text-sm leading-6 text-ink-700">Meet pets in your community who are ready for a loving home.</p><Link to="/adoption" className={`${btn} mt-5`}>Explore adoption <ArrowRight size={16} /></Link></div></section>

    <section className="grid gap-4 md:grid-cols-3">{[["They made finding a vet feel easy.", "Maya & Milo"], ["Everything for Luna, finally in one place.", "Omar & Luna"], ["The sitter updates gave us real peace of mind.", "Nour & Coco"]].map(([quote, name]) => <blockquote key={name} className={`${card} border-0 p-6`}><div className="flex gap-1 text-accent-500">{Array.from({ length: 5 }, (_, index) => <Star key={index} size={14} fill="currentColor" />)}</div><p className="mt-4 text-sm font-semibold leading-6">“{quote}”</p><footer className="mt-4 text-xs font-bold text-ink-500">{name}</footer></blockquote>)}</section>

    <section className="grid gap-4 rounded-2xl bg-primary-700 p-6 text-white sm:grid-cols-3 sm:p-8">{[["Care in one place", "Book, shop, and keep records together."], ["Local by nature", "Find services close to home."], ["Made for real life", "Simple tools for the everyday moments."]].map(([title, text], index) => <div key={title} className={`flex gap-4 ${index ? "sm:border-l sm:border-white/20 sm:pl-6" : ""}`}><ShieldCheck className="mt-1 shrink-0 text-accent-400" size={22} /><div><h3 className="font-extrabold">{title}</h3><p className="mt-1 text-xs leading-5 text-white/70">{text}</p></div></div>)}</section>

    <section className="grid gap-4 md:grid-cols-2"><div className={`${card} p-6 sm:p-7`}><div className="flex items-center justify-between"><div><p className="text-xs font-extrabold uppercase tracking-wider text-primary-700">My family</p><h2 className="mt-1 text-xl font-extrabold">My pets</h2></div><Link aria-label="Add a pet" to="/pets/new" className="grid size-10 place-items-center rounded-xl bg-primary-50 text-primary-700"><Plus size={19} /></Link></div>{pets.length ? <div className="mt-4 divide-y divide-stone-100">{pets.map((pet) => <Link key={pet.id} to={`/pets/${pet.id}`} className="flex items-center gap-3 py-3"><span className="grid size-10 place-items-center rounded-full bg-primary-50 text-primary-700"><PawPrint size={18} /></span><span className="flex-1"><b className="block text-sm">{pet.name}</b><span className="text-xs text-ink-500">{pet.type}</span></span><ArrowRight size={16} className="text-ink-500" /></Link>)}</div> : <p className="mt-4 text-sm text-ink-500">No pets added yet. Start a profile to keep their details close.</p>}</div><div className={`${card} p-6 sm:p-7`}><p className="text-xs font-extrabold uppercase tracking-wider text-primary-700">Coming up</p><h2 className="mt-1 text-xl font-extrabold">Next appointment</h2>{next ? <div className="mt-5 flex gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-xl bg-accent-50 text-accent-500"><CalendarDays size={22} /></span><div><h3 className="font-extrabold">{next.provider.name}</h3><p className="mt-1 text-sm text-ink-500">{next.date} at {next.time} · {next.pet.name}</p><Link to="/bookings" className="mt-3 inline-flex items-center text-sm font-bold text-primary-700">View booking <ArrowRight size={15} className="ml-1" /></Link></div></div> : <><p className="mt-4 text-sm text-ink-500">No appointments booked. Find a time that works for you.</p><Link to="/services" className={`${btn} mt-4`}><Clock3 size={16} /> Book a service</Link></>}</div></section>

    <section className="flex flex-col items-start justify-between gap-5 rounded-[28px] bg-[#17312f] p-7 text-white sm:flex-row sm:items-center sm:p-10"><div><p className="text-xs font-extrabold uppercase tracking-wider text-accent-400">Here when you need us</p><h2 className="mt-2 text-2xl font-extrabold sm:text-3xl">A little more peace of mind.</h2><p className="mt-2 text-sm text-white/70">Make today a good day for the ones who make yours.</p></div><Link to="/services" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-white px-5 py-2.5 text-sm font-extrabold text-primary-700">Find care <ArrowRight size={16} /></Link></section>
  </div>;
}
