import { useState } from "react";
import { Link, useParams, useNavigate } from "react-router-dom";
import { ArrowLeft, ArrowRight, Bird, CalendarDays, Check, ClipboardPlus, FileHeart, PawPrint, Plus, Printer, ShieldCheck, Syringe, UserRound, Weight } from "lucide-react";
import { useApp } from "../store.jsx";
import { btn, btn2, card, input } from "../ui.js";
import Media from "../components/Media.jsx";

const petPhotos = {
  Dog: "https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=800&q=70",
  Cat: "https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=800&q=70",
  Bird: "https://images.unsplash.com/photo-1552728089-57bdde30beb3?auto=format&fit=crop&w=800&q=70",
};

export function MyPets() {
  const { pets } = useApp();
  return <div><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-wider text-primary-700">The whole family</p><h1 className="mt-2 text-3xl font-extrabold">My pets</h1><p className="mt-2 text-sm text-ink-500">Keep the little details and health records together.</p></div><Link to="/pets/new" className={btn}><Plus size={17} /> Add a pet</Link></div>
    {pets.length ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{pets.map((pet) => <Link key={pet.id} to={`/pets/${pet.id}`} className={`${card} group overflow-hidden p-0 hover:-translate-y-1 hover:shadow-lg`}><div className="relative h-56"><Media src={petPhotos[pet.type]} alt={`${pet.name}, ${pet.type}`} className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.03]" /><span className="absolute bottom-3 left-3 rounded-full bg-white/95 px-3 py-1 text-xs font-bold text-primary-700">{pet.type}</span></div><div className="flex items-center gap-3 p-5"><span className="grid size-11 place-items-center rounded-xl bg-primary-50 text-primary-700"><PawPrint size={21} /></span><span className="flex-1"><b className="block text-base">{pet.name}</b><span className="mt-1 block text-sm text-ink-500">{pet.breed || "Breed not added"} · {pet.age} years</span></span><ArrowRight size={18} className="text-ink-500" /></div></Link>)}</div> : <div className={`${card} py-16 text-center`}><PawPrint size={30} className="mx-auto text-primary-600" /><h2 className="mt-4 text-xl font-extrabold">Your pet profiles start here</h2><p className="mt-2 text-sm text-ink-500">Add a pet to keep their details and care history in one place.</p><Link to="/pets/new" className={`${btn} mt-5`}><Plus size={16} /> Add a pet</Link></div>}</div>;
}
export function AddPet() {
  const { addPet } = useApp(); const nav = useNavigate();
  const [f, setF] = useState({ name: "", type: "Dog", breed: "", age: "", gender: "Male", weight: "" });
  const set = (k) => (e) => setF({ ...f, [k]: e.target.value });
  return <div className="mx-auto max-w-2xl"><Link to="/pets" className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-ink-500 hover:text-primary-700"><ArrowLeft size={16} /> My pets</Link><form className={`${card} space-y-5 p-6 sm:p-8`} onSubmit={(e) => { e.preventDefault(); addPet(f); nav("/pets"); }}><div><p className="text-xs font-extrabold uppercase tracking-wider text-primary-700">New family member</p><h1 className="mt-2 text-2xl font-extrabold">Add a pet</h1><p className="mt-2 text-sm text-ink-500">Start with the basics. You can keep their health records here too.</p></div>
    <div className="grid gap-4 sm:grid-cols-2"><label className="block text-xs font-bold">Pet name<input required aria-label="Pet name" className={`${input} mt-2`} placeholder="e.g. Luna" value={f.name} onChange={set("name")} /></label><label className="block text-xs font-bold">Pet type<select aria-label="Pet type" className={`${input} mt-2`} value={f.type} onChange={set("type")}>{["Dog", "Cat", "Bird", "Other"].map((type) => <option key={type}>{type}</option>)}</select></label><label className="block text-xs font-bold">Breed <span className="font-normal text-ink-500">(optional)</span><input aria-label="Breed" className={`${input} mt-2`} placeholder="Breed" value={f.breed} onChange={set("breed")} /></label><label className="block text-xs font-bold">Age in years<input required aria-label="Age" type="number" min="0" className={`${input} mt-2`} placeholder="Age" value={f.age} onChange={set("age")} /></label><label className="block text-xs font-bold">Gender<select aria-label="Gender" className={`${input} mt-2`} value={f.gender} onChange={set("gender")}><option>Male</option><option>Female</option></select></label><label className="block text-xs font-bold">Weight in kg <span className="font-normal text-ink-500">(optional)</span><input aria-label="Weight in kg" type="number" min="0" className={`${input} mt-2`} placeholder="Weight" value={f.weight} onChange={set("weight")} /></label></div><button className={`${btn} w-full sm:w-auto`}><Check size={17} /> Save pet profile</button></form></div>;
}
export function PetProfile() {
  const { id } = useParams(); const { pets, updatePet } = useApp();
  const p = pets.find((x) => x.id === +id); const [tab, setTab] = useState("Info");
  const [v, setV] = useState({ name: "", date: "", next: "" }); const [m, setM] = useState({ name: "", dose: "", end: "" });
  if (!p) return <p>Pet not found.</p>;
  return <div><Link to="/pets" className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-ink-500 hover:text-primary-700"><ArrowLeft size={16} /> My pets</Link><section className="relative isolate mb-7 flex min-h-48 items-end overflow-hidden rounded-2xl bg-[#17312f] p-6 text-white sm:p-8"><Media src={petPhotos[p.type]} alt={`${p.name}, ${p.type}`} className="absolute inset-0 -z-10 h-full w-full object-cover opacity-45" /><div className="absolute inset-0 -z-10 bg-gradient-to-r from-[#17312f] via-[#17312f]/70 to-transparent" /><span className="grid size-14 place-items-center rounded-2xl border border-white/30 bg-white/15"><PawPrint size={27} /></span><div className="ml-4"><span className="text-xs font-bold text-white/70">{p.type}{p.breed ? ` · ${p.breed}` : ""}</span><h1 className="mt-1 text-3xl font-extrabold">{p.name}</h1><p className="mt-1 text-sm text-white/75">{p.age} years old · {p.gender}</p></div></section>
    <div role="tablist" aria-label="Pet profile sections" className="mb-6 flex gap-1 overflow-x-auto rounded-xl bg-stone-100 p-1">{[["Info", UserRound], ["Medical Record", FileHeart], ["Digital Passport", ShieldCheck]].map(([title, Icon]) => <button key={title} role="tab" aria-selected={tab === title} onClick={() => setTab(title)} className={`inline-flex min-h-10 shrink-0 items-center gap-2 rounded-lg px-4 text-sm font-bold transition ${tab === title ? "bg-white text-primary-700 shadow-sm" : "text-ink-500 hover:text-ink-900"}`}><Icon size={16} />{title}</button>)}</div>
    {tab === "Info" && <div className="grid gap-4 sm:grid-cols-2">{[["Type", p.type, PawPrint], ["Breed", p.breed || "Not added", Bird], ["Age", `${p.age} years`, CalendarDays], ["Gender", p.gender, UserRound], ["Weight", p.weight ? `${p.weight} kg` : "Not added", Weight]].map(([label, value, Icon]) => <div key={label} className={`${card} flex items-center gap-4`}><span className="grid size-11 place-items-center rounded-xl bg-primary-50 text-primary-700"><Icon size={19} /></span><div><span className="block text-xs font-semibold text-ink-500">{label}</span><b className="mt-1 block">{value}</b></div></div>)}</div>}
    {tab === "Medical Record" && <div className="grid gap-5 lg:grid-cols-2"><section className={card}><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-primary-50 text-primary-700"><Syringe size={20} /></span><div><h2 className="font-extrabold">Vaccinations</h2><p className="text-xs text-ink-500">Keep track of important dates.</p></div></div>{p.vaccines.length ? <div className="mt-4 divide-y divide-stone-100">{p.vaccines.map((vaccine, index) => <div key={index} className="flex items-center justify-between gap-3 py-3 text-sm"><div><b>{vaccine.name}</b><p className="mt-1 text-xs text-ink-500">Given {vaccine.date}</p></div><span className="rounded-full bg-primary-50 px-3 py-1 text-xs font-bold text-primary-700">Next {vaccine.next || "Not set"}</span></div>)}</div> : <p className="mt-4 text-sm text-ink-500">No vaccinations recorded yet.</p>}<form className="mt-5 space-y-3 border-t border-stone-100 pt-5" onSubmit={(e) => { e.preventDefault(); updatePet(p.id, (pet) => ({ ...pet, vaccines: [...pet.vaccines, v] })); setV({ name: "", date: "", next: "" }); }}><label className="block text-xs font-bold">Vaccine name<input required aria-label="Vaccine name" className={`${input} mt-2`} placeholder="Vaccine name" value={v.name} onChange={(e) => setV({ ...v, name: e.target.value })} /></label><div className="grid gap-3 sm:grid-cols-2"><label className="block text-xs font-bold">Date given<input required aria-label="Date given" type="date" className={`${input} mt-2`} value={v.date} onChange={(e) => setV({ ...v, date: e.target.value })} /></label><label className="block text-xs font-bold">Next date<input aria-label="Next vaccination date" type="date" className={`${input} mt-2`} value={v.next} onChange={(e) => setV({ ...v, next: e.target.value })} /></label></div><button className={btn2}><Plus size={15} /> Add vaccination</button></form></section>
    <section className={card}><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-accent-50 text-accent-500"><ClipboardPlus size={20} /></span><div><h2 className="font-extrabold">Medications</h2><p className="text-xs text-ink-500">Current and previous prescriptions.</p></div></div>{p.meds.length ? <div className="mt-4 divide-y divide-stone-100">{p.meds.map((medication, index) => <div key={index} className="py-3 text-sm"><b>{medication.name}</b><p className="mt-1 text-xs text-ink-500">{medication.dose} · until {medication.end || "Not set"}</p></div>)}</div> : <p className="mt-4 text-sm text-ink-500">No medications recorded yet.</p>}<form className="mt-5 space-y-3 border-t border-stone-100 pt-5" onSubmit={(e) => { e.preventDefault(); updatePet(p.id, (pet) => ({ ...pet, meds: [...pet.meds, m] })); setM({ name: "", dose: "", end: "" }); }}><label className="block text-xs font-bold">Medicine name<input required aria-label="Medicine name" className={`${input} mt-2`} placeholder="Medicine name" value={m.name} onChange={(e) => setM({ ...m, name: e.target.value })} /></label><label className="block text-xs font-bold">Dose<input aria-label="Dose" className={`${input} mt-2`} placeholder="Dose" value={m.dose} onChange={(e) => setM({ ...m, dose: e.target.value })} /></label><label className="block text-xs font-bold">End date<input aria-label="End date" type="date" className={`${input} mt-2`} value={m.end} onChange={(e) => setM({ ...m, end: e.target.value })} /></label><button className={btn2}><Plus size={15} /> Add medication</button></form></section></div>}
    {tab === "Digital Passport" && <div className="mx-auto max-w-2xl"><div className="overflow-hidden rounded-2xl border border-primary-100 bg-white shadow-lg"><div className="flex items-center justify-between bg-primary-700 px-6 py-4 text-white"><span className="flex items-center gap-2 text-sm font-extrabold uppercase"><ShieldCheck size={19} /> PetCare digital passport</span><span className="text-xs font-bold text-white/75">PET-{String(p.id).slice(-6)}</span></div><div className="grid gap-6 p-6 sm:grid-cols-[180px_1fr] sm:p-8"><Media src={petPhotos[p.type]} alt={`${p.name}, ${p.type}`} className="aspect-square w-full rounded-xl object-cover" /><div><p className="text-xs font-extrabold uppercase tracking-wider text-primary-700">Pet identity</p><h2 className="mt-2 text-3xl font-extrabold">{p.name}</h2><p className="mt-1 text-sm text-ink-500">{p.type}{p.breed ? ` · ${p.breed}` : ""}</p><div className="mt-5 grid grid-cols-2 gap-4 border-y border-stone-100 py-4 text-sm"><div><span className="block text-xs text-ink-500">Age</span><b className="mt-1 block">{p.age} years</b></div><div><span className="block text-xs text-ink-500">Gender</span><b className="mt-1 block">{p.gender}</b></div></div><h3 className="mt-4 text-xs font-extrabold uppercase tracking-wider text-ink-500">Vaccination record</h3>{p.vaccines.length ? p.vaccines.map((vaccine, index) => <p key={index} className="mt-2 flex items-center gap-2 text-sm"><Check size={15} className="text-primary-600" /> {vaccine.name} · {vaccine.date}</p>) : <p className="mt-2 text-sm text-ink-500">No vaccinations recorded.</p>}</div></div></div><button className={`${btn2} mt-4 w-full sm:w-auto`} onClick={() => window.print()}><Printer size={16} /> Print or save PDF</button></div>}</div>;
}
