import { useEffect, useState } from "react";
import { Link, useParams, useNavigate } from "react-router-dom";
import { Activity, ArrowLeft, ArrowRight, Bird, CalendarDays, Check, ClipboardPlus, FileHeart, PawPrint, Pencil, Plus, Printer, ShieldCheck, Syringe, Trash2, UserRound, Weight } from "lucide-react";
import { useApp } from "../store.jsx";
import { btn, btn2, card, input } from "../ui.js";
import PetAvatar from "../components/PetAvatar.jsx";
import PhotoUpload from "../components/PhotoUpload.jsx";
import { Button, Modal } from "../components/ui.jsx";

function PetCardPhoto({ pet }) {
  const [failed, setFailed] = useState(false);
  useEffect(() => setFailed(false), [pet.photo]);
  if (pet.photo && !failed) return <img src={pet.photo} alt={`${pet.name}, ${pet.type}`} loading="lazy" onError={() => setFailed(true)} className="aspect-[4/3] w-full rounded-xl object-cover" />;
  return <div role="img" aria-label={`${pet.name} avatar`} className="flex aspect-[4/3] w-full flex-col items-center justify-center gap-2 overflow-hidden rounded-xl bg-primary-50 text-primary-700"><span className="text-6xl font-extrabold">{pet.name?.trim()?.slice(0, 1).toUpperCase() || "?"}</span><PawPrint aria-hidden="true" size={30} /></div>;
}

function PetFormModal({ pet, onClose, onSaved }) {
  const { updatePetInfo } = useApp();
  const [form, setForm] = useState({ name: pet?.name || "", type: pet?.type || "Dog", breed: pet?.breed || "", age: pet?.age ?? "", gender: pet?.gender || "Male", weight: pet?.weight || "", healthStatus: pet?.healthStatus || "Healthy", notes: pet?.notes || "", photo: pet?.photo || "" });
  const [saving, setSaving] = useState(false);
  useEffect(() => {
    if (pet) setForm({ name: pet.name || "", type: pet.type || "Dog", breed: pet.breed || "", age: pet.age ?? "", gender: pet.gender || "Male", weight: pet.weight || "", healthStatus: pet.healthStatus || "Healthy", notes: pet.notes || "", photo: pet.photo || "" });
  }, [pet]);
  const set = (key) => (event) => setForm((current) => ({ ...current, [key]: event.target.value }));
  return <Modal open={Boolean(pet)} onClose={onClose} title={pet ? `Edit ${pet.name}` : "Edit pet"}>
    <form className="space-y-4" onSubmit={async (event) => { event.preventDefault(); if (!pet) return; setSaving(true); try { await updatePetInfo(pet.id, { ...form, age: Number(form.age), weight: form.weight ? Number(form.weight) : "" }); onSaved(form.name); } finally { setSaving(false); } }}>
      <label className="block text-xs font-bold">Pet photo <span className="font-normal text-ink-500">(optional)</span><div className="mt-2"><PhotoUpload value={form.photo} onChange={(photo) => setForm((current) => ({ ...current, photo }))} label="Pet photo" /></div></label>
      <div className="grid gap-3 sm:grid-cols-2"><label className="block text-xs font-bold">Pet name<input required className={`${input} mt-2`} value={form.name} onChange={set("name")} /></label><label className="block text-xs font-bold">Pet type<select className={`${input} mt-2`} value={form.type} onChange={set("type")}>{["Dog", "Cat", "Bird", "Other"].map((type) => <option key={type}>{type}</option>)}</select></label><label className="block text-xs font-bold">Breed<input className={`${input} mt-2`} value={form.breed} onChange={set("breed")} /></label><label className="block text-xs font-bold">Age in years<input required type="number" min="0" className={`${input} mt-2`} value={form.age} onChange={set("age")} /></label><label className="block text-xs font-bold">Gender<select className={`${input} mt-2`} value={form.gender} onChange={set("gender")}><option>Male</option><option>Female</option></select></label><label className="block text-xs font-bold">Weight in kg<input type="number" min="0" className={`${input} mt-2`} value={form.weight} onChange={set("weight")} /></label><label className="block text-xs font-bold">Health status<select aria-label="Health status" className={`${input} mt-2`} value={form.healthStatus} onChange={set("healthStatus")}><option>Healthy</option><option>Monitoring</option><option>Under treatment</option></select></label><label className="block text-xs font-bold">Health notes<textarea aria-label="Health notes" rows="3" className={`${input} mt-2`} value={form.notes} onChange={set("notes")} /></label></div>
      <div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? "Saving..." : "Save changes"}</Button></div>
    </form>
  </Modal>;
}

export function MyPets() {
  const { pets, deletePet, bookings, showToast, user } = useApp();
  const [editingPet, setEditingPet] = useState(null);
  const [deletingPet, setDeletingPet] = useState(null);
  const [cancelBookings, setCancelBookings] = useState(true);
  const removePet = async () => { await deletePet(deletingPet.id, { cancelBookings }); showToast(`${deletingPet.name} was deleted.`); setDeletingPet(null); };
  if (!user) return <div className={`${card} mx-auto max-w-lg py-14 text-center`}><PawPrint size={30} className="mx-auto text-primary-600" /><h1 className="mt-4 text-2xl font-extrabold">Please log in to view your pets</h1><p className="mt-2 text-sm text-ink-500">Your pet profiles and medical records are saved with your account.</p><Link to="/login" state={{ from: "/pets" }} className={`${btn} mt-5`}>Log in</Link></div>;
  return <div><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-wider text-primary-700">The whole family</p><h1 className="mt-2 text-3xl font-extrabold">My pets</h1><p className="mt-2 text-sm text-ink-500">Keep the little details and health records together.</p></div><Link to="/pets/new" className={btn}><Plus size={17} /> Add a pet</Link></div>
    {pets.length ? <div className="grid items-stretch gap-5 sm:grid-cols-2 lg:grid-cols-3">{pets.map((pet) => <article key={pet.id} className={`${card} flex h-full flex-col gap-4 p-4 transition hover:-translate-y-1 hover:shadow-lg`}><Link to={`/pets/${pet.id}`} aria-label={`View ${pet.name}'s profile`} className="block overflow-hidden rounded-xl"><PetCardPhoto pet={pet} /></Link><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="truncate text-base font-extrabold">{pet.name}</h2><p className="mt-1 text-sm text-ink-500">{pet.breed || "Breed not added"} · {pet.age} years</p></div><span className="shrink-0 rounded-full bg-primary-50 px-2.5 py-1 text-[11px] font-bold text-primary-700">{pet.type}</span></div><div className="mt-auto grid grid-cols-3 gap-2 border-t border-stone-100 pt-3"><button aria-label={`Edit ${pet.name}`} className="inline-flex min-h-9 items-center justify-center gap-1.5 rounded-lg text-xs font-bold text-ink-700 hover:bg-primary-50 hover:text-primary-700" onClick={() => setEditingPet(pet)}><Pencil size={14} /> Edit</button><button aria-label={`Delete ${pet.name}`} className="inline-flex min-h-9 items-center justify-center gap-1.5 rounded-lg text-xs font-bold text-ink-700 hover:bg-red-50 hover:text-danger-600" onClick={() => { setCancelBookings(true); setDeletingPet(pet); }}><Trash2 size={14} /> Delete</button><Link aria-label={`View ${pet.name}'s profile`} to={`/pets/${pet.id}`} className="inline-flex min-h-9 items-center justify-center gap-1.5 rounded-lg text-xs font-bold text-ink-700 hover:bg-stone-100"><ArrowRight size={14} /> <span className="whitespace-nowrap">View profile</span></Link></div></article>)}</div> : <div className={`${card} py-16 text-center`}><PawPrint size={30} className="mx-auto text-primary-600" /><h2 className="mt-4 text-xl font-extrabold">Your pet profiles start here</h2><p className="mt-2 text-sm text-ink-500">Add a pet to keep their details and care history in one place.</p><Link to="/pets/new" className={`${btn} mt-5`}><Plus size={16} /> Add a pet</Link></div>}
    <PetFormModal pet={editingPet} onClose={() => setEditingPet(null)} onSaved={(name) => { setEditingPet(null); showToast(`${name} was updated.`); }} />
    <Modal open={Boolean(deletingPet)} onClose={() => setDeletingPet(null)} title={deletingPet ? `Delete ${deletingPet.name}?` : "Delete pet?"}>{deletingPet && <><p className="text-sm leading-6 text-ink-500">This also removes their medical record and passport.</p>{bookings.filter((booking) => booking.pet?.id === deletingPet.id && booking.status === "Upcoming").length > 0 && <label className="mt-4 flex items-start gap-3 rounded-xl bg-accent-50 p-4 text-sm text-ink-700"><input type="checkbox" className="mt-1 accent-primary-600" checked={cancelBookings} onChange={(event) => setCancelBookings(event.target.checked)} />Cancel {bookings.filter((booking) => booking.pet?.id === deletingPet.id && booking.status === "Upcoming").length} upcoming booking(s) too</label>}<div className="mt-6 flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => setDeletingPet(null)}>Keep pet</Button><Button type="button" variant="danger" onClick={removePet}><Trash2 size={16} /> Delete pet</Button></div></>}</Modal>
    </div>;
}
export function AddPet() {
  const { addPet, createPet, user } = useApp(); const nav = useNavigate();
  const [f, setF] = useState({ name: "", type: "Dog", breed: "", age: "", gender: "Male", weight: "", healthStatus: "Healthy", notes: "", photo: "" });
  const set = (k) => (e) => setF({ ...f, [k]: e.target.value });
  const [saving, setSaving] = useState(false);
  if (!user) return <div className={`${card} mx-auto max-w-lg py-14 text-center`}><PawPrint size={30} className="mx-auto text-primary-600" /><h1 className="mt-4 text-2xl font-extrabold">Please log in to add a pet</h1><Link to="/login" state={{ from: "/pets/new" }} className={`${btn} mt-5`}>Log in</Link></div>;
  return <div className="mx-auto max-w-2xl"><Link to="/pets" className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-ink-500 hover:text-primary-700"><ArrowLeft size={16} /> My pets</Link><form className={`${card} space-y-5 p-6 sm:p-8`} onSubmit={async (e) => { e.preventDefault(); setSaving(true); try { if (createPet) await createPet(f); else addPet(f); nav("/pets"); } finally { setSaving(false); } }}><div><p className="text-xs font-extrabold uppercase tracking-wider text-primary-700">New family member</p><h1 className="mt-2 text-2xl font-extrabold">Add a pet</h1><p className="mt-2 text-sm text-ink-500">Start with the basics. You can keep their health records here too.</p></div>
    <div><span className="mb-2 block text-xs font-bold text-ink-700">Pet photo <span className="font-normal text-ink-500">(optional)</span></span><PhotoUpload value={f.photo} onChange={(photo) => setF((current) => ({ ...current, photo }))} label="Pet photo" /></div>
    <div className="grid gap-4 sm:grid-cols-2"><label className="block text-xs font-bold">Pet name<input required aria-label="Pet name" className={`${input} mt-2`} placeholder="e.g. Luna" value={f.name} onChange={set("name")} /></label><label className="block text-xs font-bold">Pet type<select aria-label="Pet type" className={`${input} mt-2`} value={f.type} onChange={set("type")}>{["Dog", "Cat", "Bird", "Other"].map((type) => <option key={type}>{type}</option>)}</select></label><label className="block text-xs font-bold">Breed <span className="font-normal text-ink-500">(optional)</span><input aria-label="Breed" className={`${input} mt-2`} placeholder="Breed" value={f.breed} onChange={set("breed")} /></label><label className="block text-xs font-bold">Age in years<input required aria-label="Age" type="number" min="0" className={`${input} mt-2`} placeholder="Age" value={f.age} onChange={set("age")} /></label><label className="block text-xs font-bold">Gender<select aria-label="Gender" className={`${input} mt-2`} value={f.gender} onChange={set("gender")}><option>Male</option><option>Female</option></select></label><label className="block text-xs font-bold">Weight in kg <span className="font-normal text-ink-500">(optional)</span><input aria-label="Weight in kg" type="number" min="0" className={`${input} mt-2`} placeholder="Weight" value={f.weight} onChange={set("weight")} /></label><label className="block text-xs font-bold">Health status<select aria-label="Health status" className={`${input} mt-2`} value={f.healthStatus} onChange={set("healthStatus")}><option>Healthy</option><option>Monitoring</option><option>Under treatment</option></select></label><label className="block text-xs font-bold">Health notes<textarea aria-label="Health notes" rows="3" className={`${input} mt-2`} value={f.notes} onChange={set("notes")} /></label></div><button disabled={saving} className={`${btn} w-full sm:w-auto`}>{saving ? "Saving..." : <><Check size={17} /> Save pet profile</>}</button></form></div>;
}
export function PetProfile() {
  const { id } = useParams(); const { pets, deletePet, bookings, addVaccine, addMedication, deleteVaccine, deleteMedication, addMedicalVisit, deleteMedicalVisit, showToast, user } = useApp(); const nav = useNavigate();
  const p = pets.find((x) => x.id === +id); const [tab, setTab] = useState("Info");
  const [v, setV] = useState({ name: "", date: "", next: "" }); const [m, setM] = useState({ name: "", dose: "", time: "", end: "" }); const [visit, setVisit] = useState({ date: "", provider: "", reason: "", diagnosis: "", treatment: "", notes: "" });
  const [editing, setEditing] = useState(false); const [deleting, setDeleting] = useState(false); const [cancelBookings, setCancelBookings] = useState(true); const [recordToDelete, setRecordToDelete] = useState(null); const [visitOpen, setVisitOpen] = useState(false); const [visitDetails, setVisitDetails] = useState(null); const [visitDelete, setVisitDelete] = useState(null);
  if (!user) return <div className={`${card} mx-auto max-w-lg py-14 text-center`}><PawPrint size={30} className="mx-auto text-primary-600" /><h1 className="mt-4 text-2xl font-extrabold">Please log in to view this pet</h1><Link to="/login" state={{ from: `/pets/${id}` }} className={`${btn} mt-5`}>Log in</Link></div>;
  if (!p) return <p>Pet not found.</p>;
  const pendingBookings = bookings.filter((booking) => booking.pet?.id === p.id && booking.status === "Upcoming");
  const removePet = async () => { await deletePet(p.id, { cancelBookings }); setDeleting(false); showToast(`${p.name} was deleted.`); nav("/pets"); };
  const removeMedicalRecord = async () => { if (recordToDelete.type === "vaccine") await deleteVaccine(p.id, recordToDelete.index); else await deleteMedication(p.id, recordToDelete.index); showToast(`${recordToDelete.label} deleted.`); setRecordToDelete(null); };
  const saveVisit = async (event) => { event.preventDefault(); await addMedicalVisit(p.id, visit); setVisit({ date: "", provider: "", reason: "", diagnosis: "", treatment: "", notes: "" }); setVisitOpen(false); showToast("Veterinary visit added."); };
  return <div><Link to="/pets" className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-ink-500 hover:text-primary-700"><ArrowLeft size={16} /> My pets</Link><section className="relative mb-7 flex min-h-48 items-end rounded-2xl bg-[#17312f] p-6 text-white sm:p-8"><PetAvatar name={p.name} photo={p.photo} className="size-14 rounded-2xl border border-white/30" iconSize={17} alt={`${p.name}, ${p.type}`} /><div className="ml-4"><span className="text-xs font-bold text-white/70">{p.type}{p.breed ? ` · ${p.breed}` : ""}</span><h1 className="mt-1 text-3xl font-extrabold">{p.name}</h1><p className="mt-1 text-sm text-white/75">{p.age} years old · {p.gender}</p></div><div className="ms-auto flex gap-2"><Button type="button" variant="secondary" size="sm" onClick={() => setEditing(true)}><Pencil size={15} /> Edit pet</Button><Button type="button" variant="danger" size="sm" onClick={() => { setCancelBookings(true); setDeleting(true); }}><Trash2 size={15} /> Delete</Button></div></section>
    <div role="tablist" aria-label="Pet profile sections" className="mb-6 flex gap-1 overflow-x-auto rounded-xl bg-stone-100 p-1">{[["Info", UserRound], ["Medical Record", FileHeart], ["Digital Passport", ShieldCheck]].map(([title, Icon]) => <button key={title} role="tab" aria-selected={tab === title} onClick={() => setTab(title)} className={`inline-flex min-h-10 shrink-0 items-center gap-2 rounded-lg px-4 text-sm font-bold transition ${tab === title ? "bg-white text-primary-700 shadow-sm" : "text-ink-500 hover:text-ink-900"}`}><Icon size={16} />{title}</button>)}</div>
    {tab === "Info" && <><div className="grid gap-4 sm:grid-cols-2">{[["Type", p.type, PawPrint], ["Breed", p.breed || "Not added", Bird], ["Age", `${p.age} years`, CalendarDays], ["Gender", p.gender, UserRound], ["Weight", p.weight ? `${p.weight} kg` : "Not added", Weight], ["Health", p.healthStatus || "Healthy", Activity]].map(([label, value, Icon]) => <div key={label} className={`${card} flex items-center gap-4`}><span className="grid size-11 place-items-center rounded-xl bg-primary-50 text-primary-700"><Icon size={19} /></span><div><span className="block text-xs font-semibold text-ink-500">{label}</span><b className="mt-1 block">{value}</b></div></div>)}</div>{p.notes && <section className={`${card} mt-4`}><h2 className="font-extrabold">Health notes</h2><p className="mt-2 text-sm leading-6 text-ink-500">{p.notes}</p></section>}<Link to="/calendar" className={`${btn2} mt-4`}><CalendarDays size={16} /> Open pet calendar</Link></>}
    {tab === "Medical Record" && <section className={`${card} mt-5`}><div className="flex items-center justify-between gap-3"><div><h2 className="font-extrabold">Veterinary visit history</h2><p className="mt-1 text-xs text-ink-500">Keep diagnoses and treatments together.</p></div><Button type="button" size="sm" onClick={() => setVisitOpen(true)}><Plus size={15} /> Add visit</Button></div>{(p.medicalVisits || []).length ? <div className="mt-4 divide-y divide-stone-100">{p.medicalVisits.map((record) => <div key={record.id} className="flex items-center justify-between gap-3 py-3"><button type="button" onClick={() => setVisitDetails(record)} className="min-w-0 text-left"><span className="block truncate text-sm font-bold">{record.reason || "Veterinary visit"} · {record.provider}</span><span className="mt-1 block text-xs text-ink-500">{record.date}</span></button><button type="button" aria-label={`Delete visit ${record.reason}`} onClick={() => setVisitDelete(record)} className="grid size-8 shrink-0 place-items-center rounded-lg text-ink-500 hover:bg-red-50 hover:text-danger-600"><Trash2 size={15} /></button></div>)}</div> : <p className="mt-4 text-sm text-ink-500">No veterinary visits recorded yet.</p>}</section>}
    <Modal open={visitOpen} onClose={() => setVisitOpen(false)} title="Add veterinary visit"><form className="space-y-3" onSubmit={saveVisit}><label className="block text-xs font-bold">Date<input required type="date" className={`${input} mt-2`} value={visit.date} onChange={(event) => setVisit({ ...visit, date: event.target.value })} /></label>{[["provider", "Clinic / veterinarian"], ["reason", "Reason"], ["diagnosis", "Diagnosis"], ["treatment", "Treatment"], ["notes", "Notes"]].map(([key, label]) => <label key={key} className="block text-xs font-bold">{label}{key === "notes" ? <textarea rows="2" className={`${input} mt-2`} value={visit[key]} onChange={(event) => setVisit({ ...visit, [key]: event.target.value })} /> : <input required={key === "provider" || key === "reason"} className={`${input} mt-2`} value={visit[key]} onChange={(event) => setVisit({ ...visit, [key]: event.target.value })} />}</label>)}<div className="flex justify-end"><Button>Add visit</Button></div></form></Modal>
    <Modal open={Boolean(visitDetails)} onClose={() => setVisitDetails(null)} title="Veterinary visit details">{visitDetails && <div className="space-y-3 text-sm"><p><strong>Date:</strong> {visitDetails.date}</p><p><strong>Clinic / veterinarian:</strong> {visitDetails.provider}</p><p><strong>Reason:</strong> {visitDetails.reason}</p><p><strong>Diagnosis:</strong> {visitDetails.diagnosis || "Not recorded"}</p><p><strong>Treatment:</strong> {visitDetails.treatment || "Not recorded"}</p><p><strong>Notes:</strong> {visitDetails.notes || "None"}</p></div>}</Modal>
    <Modal open={Boolean(visitDelete)} onClose={() => setVisitDelete(null)} title="Delete this visit?"><p className="text-sm text-ink-500">This visit will be removed from {p.name}'s medical record.</p><div className="mt-5 flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => setVisitDelete(null)}>Keep visit</Button><Button type="button" variant="danger" onClick={async () => { await deleteMedicalVisit(p.id, visitDelete.id); setVisitDelete(null); showToast("Visit deleted."); }}>Delete visit</Button></div></Modal>
    {tab === "Medical Record" && <div className="grid gap-5 lg:grid-cols-2"><section className={card}><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-primary-50 text-primary-700"><Syringe size={20} /></span><div><h2 className="font-extrabold">Vaccinations</h2><p className="text-xs text-ink-500">Keep track of important dates.</p></div></div>{p.vaccines.length ? <div className="mt-4 divide-y divide-stone-100">{p.vaccines.map((vaccine, index) => <div key={`${vaccine.name}-${index}`} className="flex items-center justify-between gap-3 py-3 text-sm"><div><b>{vaccine.name}</b><p className="mt-1 text-xs text-ink-500">Given {vaccine.date} · next {vaccine.next || "not set"}</p></div><button type="button" aria-label={`Delete vaccination ${vaccine.name}`} onClick={() => setRecordToDelete({ type: "vaccine", index, label: vaccine.name })} className="grid size-8 place-items-center rounded-lg text-ink-500 hover:bg-red-50"><Trash2 size={15} /></button></div>)}</div> : <p className="mt-4 text-sm text-ink-500">No vaccinations recorded yet.</p>}<form className="mt-5 space-y-3 border-t border-stone-100 pt-5" onSubmit={async (event) => { event.preventDefault(); await addVaccine(p.id, v); setV({ name: "", date: "", next: "" }); showToast("Vaccination added."); }}><label className="block text-xs font-bold">Vaccine name<input required className={`${input} mt-2`} value={v.name} onChange={(event) => setV({ ...v, name: event.target.value })} /></label><div className="grid gap-3 sm:grid-cols-2"><label className="block text-xs font-bold">Date given<input required type="date" className={`${input} mt-2`} value={v.date} onChange={(event) => setV({ ...v, date: event.target.value })} /></label><label className="block text-xs font-bold">Next date<input type="date" className={`${input} mt-2`} value={v.next} onChange={(event) => setV({ ...v, next: event.target.value })} /></label></div><Button type="submit" variant="secondary"><Plus size={15} /> Add vaccination</Button></form></section>
    <section className={card}><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-accent-50 text-accent-500"><ClipboardPlus size={20} /></span><div><h2 className="font-extrabold">Medications</h2><p className="text-xs text-ink-500">Current and previous prescriptions.</p></div></div>{p.meds.length ? p.meds.map((medication, index) => <p key={index} className="mt-2 flex items-center gap-2 text-sm"><Check size={15} className="text-primary-600" /> {medication.name} · {medication.dose}{medication.time ? ` · ${medication.time}` : ""} · until {medication.end || "Not set"}</p>) : <p className="mt-2 text-sm text-ink-500">No medications recorded yet.</p>}<form className="mt-5 space-y-3 border-t border-stone-100 pt-5" onSubmit={async (e) => { e.preventDefault(); await addMedication(p.id, m); setM({ name: "", dose: "", time: "", end: "" }); showToast("Medication added."); }}><label className="block text-xs font-bold">Medicine name<input required aria-label="Medicine name" className={`${input} mt-2`} placeholder="Medicine name" value={m.name} onChange={(e) => setM({ ...m, name: e.target.value })} /></label><label className="block text-xs font-bold">Dose<input aria-label="Dose" className={`${input} mt-2`} placeholder="Dose" value={m.dose} onChange={(e) => setM({ ...m, dose: e.target.value })} /></label><label className="block text-xs font-bold">End date<input aria-label="End date" type="date" className={`${input} mt-2`} value={m.end} onChange={(e) => setM({ ...m, end: e.target.value })} /></label><label className="block text-xs font-bold">Medication time<input aria-label="Medication time" type="time" className={`${input} mt-2`} value={m.time} onChange={(e) => setM({ ...m, time: e.target.value })} /></label><button className={btn2}><Plus size={15} /> Add medication</button></form></section></div>}
    {tab === "Digital Passport" && <div className="mx-auto max-w-2xl"><div className="overflow-hidden rounded-2xl border border-primary-100 bg-white shadow-lg"><div className="flex items-center justify-between bg-primary-700 px-6 py-4 text-white"><span className="flex items-center gap-2 text-sm font-extrabold uppercase"><ShieldCheck size={19} /> PetCare digital passport</span><span className="text-xs font-bold text-white/75">PET-{String(p.id).slice(-6)}</span></div><div className="grid gap-6 p-6 sm:grid-cols-[180px_1fr] sm:p-8"><PetAvatar name={p.name} photo={p.photo} className="aspect-square w-full rounded-xl" iconSize={28} alt={`${p.name}, ${p.type}`} /><div><p className="text-xs font-extrabold uppercase tracking-wider text-primary-700">Pet identity</p><h2 className="mt-2 text-3xl font-extrabold">{p.name}</h2><p className="mt-1 text-sm text-ink-500">{p.type}{p.breed ? ` · ${p.breed}` : ""}</p><div className="mt-5 grid grid-cols-2 gap-4 border-y border-stone-100 py-4 text-sm"><div><span className="block text-xs text-ink-500">Age</span><b className="mt-1 block">{p.age} years</b></div><div><span className="block text-xs text-ink-500">Gender</span><b className="mt-1 block">{p.gender}</b></div></div><h3 className="mt-4 text-xs font-extrabold uppercase tracking-wider text-ink-500">Vaccination record</h3>{p.vaccines.length ? p.vaccines.map((vaccine, index) => <p key={index} className="mt-2 flex items-center gap-2 text-sm"><Check size={15} className="text-primary-600" /> {vaccine.name} · {vaccine.date}</p>) : <p className="mt-2 text-sm text-ink-500">No vaccinations recorded.</p>}
      <div className="mt-4 rounded-lg bg-stone-50 p-3"><p className="text-xs font-extrabold uppercase tracking-wider text-primary-700">Health summary</p><p className="mt-2 text-sm"><strong>General health:</strong> {p.healthStatus || "Healthy"}</p><p className="mt-2 text-xs text-ink-500"><strong>Owner:</strong> {user.name || "Pet parent"} · {user.phone || "Phone not added"} · {user.city || "City not added"}</p>{(p.meds || []).length > 0 && <p className="mt-2 text-xs text-ink-500"><strong>Current medications:</strong> {p.meds.map((med) => `${med.name}${med.dose ? ` (${med.dose})` : ""}`).join(", ")}</p>}</div>
      </div></div></div><button className={`${btn2} mt-4 w-full sm:w-auto`} onClick={() => window.print()}><Printer size={16} /> Print or save PDF</button></div>}
      <PetFormModal pet={editing ? p : null} onClose={() => setEditing(false)} onSaved={(name) => { setEditing(false); showToast(`${name} was updated.`); }} />
      <Modal open={deleting} onClose={() => setDeleting(false)} title={`Delete ${p.name}?`}><p className="text-sm leading-6 text-ink-500">This also removes their medical record and passport.</p>{pendingBookings.length > 0 && <label className="mt-4 flex items-start gap-3 rounded-xl bg-accent-50 p-4 text-sm text-ink-700"><input type="checkbox" className="mt-1 accent-primary-600" checked={cancelBookings} onChange={(event) => setCancelBookings(event.target.checked)} />Cancel {pendingBookings.length} upcoming booking(s) too</label>}<div className="mt-6 flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => setDeleting(false)}>Keep pet</Button><Button type="button" variant="danger" onClick={removePet}><Trash2 size={16} /> Delete pet</Button></div></Modal>
      <Modal open={Boolean(recordToDelete)} onClose={() => setRecordToDelete(null)} title={`Delete ${recordToDelete?.label || "record"}?`}><p className="text-sm leading-6 text-ink-500">This record will be removed from {p.name}'s medical history.</p><div className="mt-6 flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => setRecordToDelete(null)}>Keep record</Button><Button type="button" variant="danger" onClick={removeMedicalRecord}><Trash2 size={16} /> Delete record</Button></div></Modal>
    </div>;
}
