import { useState } from "react";
import { Link, useParams, useNavigate, useSearchParams } from "react-router-dom";
import { Activity, ArrowLeft, ArrowRight, Bath, CalendarDays, Check, Clock3, Heart, Home, MapPin, Scissors, Search, ShieldCheck, Star, Stethoscope, UserRound } from "lucide-react";
import { providers } from "../data.js";
import { useApp } from "../store.jsx";
import Media from "../components/Media.jsx";
import PetAvatar from "../components/PetAvatar.jsx";
import { btn, btn2, card, input } from "../ui.js";
export const titles = { vet: "Veterinary", grooming: "Grooming", sitting: "Pet Sitting" };
const serviceIcons = { vet: Stethoscope, grooming: Scissors, sitting: Home };
const providerIcons = { clinic: Activity, stethoscope: Stethoscope, hospital: Activity, scissors: Scissors, bath: Bath, home: Home, walk: UserRound };

export function ServicesHome() {
  const choices = [["vet", "Veterinary", "Checkups, vaccinations and expert health support.", Stethoscope], ["grooming", "Grooming", "Baths and grooming to keep them comfortable.", Scissors], ["sitting", "Pet sitting", "Trusted visits, walks and time at home.", Home]];
  return <div><p className="text-xs font-extrabold uppercase tracking-wider text-primary-700">Services</p><h1 className="mt-2 text-3xl font-extrabold">Care for every kind of day</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-ink-500">Choose the support you need and find a trusted provider near you.</p><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{choices.map(([type, title, description, Icon]) => <Link key={type} to={`/services/${type}`} className={`${card} group overflow-hidden p-0 hover:-translate-y-1 hover:shadow-lg`}><div className="relative h-48"><Media src={providers.find((provider) => provider.type === type)?.image} alt={`${title} service`} className="h-full w-full object-cover" /><span className="absolute bottom-4 left-4 grid size-12 place-items-center rounded-2xl bg-white text-primary-700 shadow"><Icon size={23} /></span></div><div className="p-5"><h2 className="text-lg font-extrabold">{title}</h2><p className="mt-2 text-sm leading-6 text-ink-500">{description}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-primary-700">Browse providers <ArrowRight size={16} /></span></div></Link>)}</div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Link to="/emergency" className="flex items-center gap-4 rounded-2xl border border-red-100 bg-red-50 p-5 text-danger-600"><span className="grid size-12 place-items-center rounded-xl bg-white"><Activity size={22} /></span><span><b className="block">Emergency care</b><span className="mt-1 block text-xs text-red-800/70">Find local clinics and call for help.</span></span><ArrowRight className="ml-auto" size={18} /></Link><Link to="/ai" className="flex items-center gap-4 rounded-2xl border border-primary-100 bg-primary-50 p-5 text-primary-700"><span className="grid size-12 place-items-center rounded-xl bg-white"><Heart size={22} /></span><span><b className="block">Pet care assistant</b><span className="mt-1 block text-xs text-ink-500">Ask a question or explore the demo.</span></span><ArrowRight className="ml-auto" size={18} /></Link></div></div>;
}

export function ServiceList() {
  const { type } = useParams();
  const [searchParams] = useSearchParams();
  const [q, setQ] = useState(""); const [city, setCity] = useState(searchParams.get("city") || ""); const [max, setMax] = useState(""); const [rating, setRating] = useState("");
  const list = providers.filter((p) => p.type === type && p.name.toLowerCase().includes(q.toLowerCase()) && (!city || p.city === city) && (!max || p.price <= +max) && (!rating || p.rating >= +rating));
  const Icon = serviceIcons[type] || Stethoscope;
  return <div><Link to="/services" className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-ink-500 hover:text-primary-700"><ArrowLeft size={16} /> All services</Link><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-wider text-primary-700">Find your fit</p><h1 className="mt-2 text-3xl font-extrabold">{titles[type] || "Service providers"}</h1><p className="mt-2 text-sm text-ink-500">Local professionals, ready to help your pet feel their best.</p></div><span className="rounded-full bg-primary-50 px-3 py-1.5 text-xs font-bold text-primary-700">{list.length} {list.length === 1 ? "provider" : "providers"}</span></div>
    <div className="mb-7 grid gap-3 rounded-2xl border border-stone-200 bg-white p-4 sm:grid-cols-2 lg:grid-cols-4"><label className="relative sm:col-span-2 lg:col-span-1"><span className="sr-only">Search providers</span><Search size={17} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-ink-500" /><input aria-label="Search providers" className={`${input} pl-10`} placeholder="Search providers" value={q} onChange={(e) => setQ(e.target.value)} /></label>
      <label><span className="sr-only">City</span><select aria-label="City" className={input} value={city} onChange={(e) => setCity(e.target.value)}><option value="">All cities</option><option>Cairo</option><option>Giza</option><option>Alexandria</option></select></label>
      <label><span className="sr-only">Maximum price</span><input aria-label="Maximum price" className={input} type="number" min="0" placeholder="Max price (EGP)" value={max} onChange={(e) => setMax(e.target.value)} /></label>
      <label><span className="sr-only">Minimum rating</span><select aria-label="Minimum rating" className={input} value={rating} onChange={(e) => setRating(e.target.value)}><option value="">Any rating</option><option value="4.5">4.5+ stars</option><option value="4.8">4.8+ stars</option></select></label></div>
    {list.length ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{list.map((provider) => { const ProviderIcon = providerIcons[provider.icon] || Icon; return <Link key={provider.id} to={`/services/${type}/${provider.id}`} className={`${card} group overflow-hidden p-0 hover:-translate-y-1 hover:shadow-lg`}><div className="relative h-52"><Media src={provider.image} alt={provider.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.03]" /><span className="absolute left-3 top-3 grid size-10 place-items-center rounded-xl bg-white text-primary-700 shadow-sm"><ProviderIcon size={19} /></span><span className="absolute right-3 top-3 flex items-center gap-1 rounded-full bg-white/95 px-2.5 py-1 text-xs font-extrabold"><Star size={13} fill="currentColor" className="text-accent-500" />{provider.rating}</span></div><div className="p-5"><h2 className="text-base font-extrabold">{provider.name}</h2><p className="mt-1 flex items-center gap-1 text-sm text-ink-500"><MapPin size={14} /> {provider.city}</p><p className="mt-3 line-clamp-2 text-sm leading-6 text-ink-500">{provider.info}</p><div className="mt-4 flex items-center justify-between border-t border-stone-100 pt-4"><span className="text-sm text-ink-500">From <b className="text-ink-900">{provider.price} EGP</b></span><span className="inline-flex items-center gap-2 rounded-lg bg-primary-50 px-3 py-2 text-xs font-extrabold text-primary-700">View & book <ArrowRight size={14} /></span></div></div></Link>; })}</div> : <div className={`${card} py-16 text-center`}><span className="mx-auto grid size-14 place-items-center rounded-full bg-primary-50 text-primary-600"><Search size={23} /></span><h2 className="mt-4 text-lg font-extrabold">No providers match those filters</h2><p className="mt-2 text-sm text-ink-500">Try changing the city, rating or price range.</p><button className={`${btn2} mt-4`} onClick={() => { setQ(""); setCity(""); setMax(""); setRating(""); }}>Clear filters</button></div>}</div>;
}

export function ServiceDetails() {
  const { id } = useParams(); const nav = useNavigate();
  const { pets, createBooking } = useApp();
  const p = providers.find((x) => x.id === +id);
  const [f, setF] = useState({ pet: pets[0]?.id || "", date: "", time: "", notes: "" });
  const [saving, setSaving] = useState(false);
  const set = (k) => (e) => setF({ ...f, [k]: e.target.value });
  if (!p) return <div className={`${card} py-16 text-center`}><h1 className="text-2xl font-extrabold">Provider not found</h1><Link to="/services" className={`${btn} mt-5`}>Browse services</Link></div>;
  const submit = async (e) => { e.preventDefault(); setSaving(true); try { await createBooking({ provider: p, pet: pets.find((x) => x.id === +f.pet), date: f.date, time: f.time, notes: f.notes }); nav("/bookings", { state: { toast: "Your appointment request is confirmed." } }); } finally { setSaving(false); } };
  const ProviderIcon = providerIcons[p.icon] || Stethoscope;
  return <div><Link to={`/services/${p.type}`} className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-ink-500 hover:text-primary-700"><ArrowLeft size={16} /> Back to {titles[p.type]}</Link><div className="grid items-start gap-7 lg:grid-cols-[1fr_380px]"><div className="min-w-0"><div className="relative h-64 overflow-hidden rounded-2xl sm:h-80"><Media src={p.image} alt={p.name} className="h-full w-full object-cover" /><span className="absolute bottom-4 left-4 grid size-12 place-items-center rounded-xl bg-white text-primary-700 shadow"><ProviderIcon size={23} /></span></div><div className="mt-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><span className="text-xs font-extrabold uppercase tracking-wider text-primary-700">{titles[p.type]}</span><h1 className="mt-1 text-3xl font-extrabold">{p.name}</h1></div><span className="flex items-center gap-1 rounded-full bg-accent-50 px-3 py-2 text-sm font-extrabold"><Star size={16} fill="currentColor" className="text-accent-500" /> {p.rating}</span></div><p className="mt-3 flex items-center gap-2 text-sm text-ink-500"><MapPin size={16} /> {p.city}<span className="text-stone-300">·</span><ShieldCheck size={16} className="text-primary-600" /> Trusted provider</p><p className="mt-5 max-w-2xl text-sm leading-7 text-ink-700">{p.info} We make it easy to plan the right care for your pet, with clear pricing and convenient appointments.</p></div><div className="mt-8 grid gap-4 lg:grid-cols-2">
  <section className="rounded-2xl border border-stone-200 bg-white p-5">
    <p className="text-xs font-extrabold uppercase tracking-wider text-primary-700">Services &amp; pricing</p>
    <h2 className="mt-2 text-lg font-extrabold">{titles[p.type]} care</h2>
    <p className="mt-2 text-sm leading-6 text-ink-500">{p.info}</p>
    <div className="mt-4 flex items-center justify-between border-t border-stone-100 pt-4 text-sm"><span className="font-semibold">Starting service price</span><b className="text-primary-700">{p.price} EGP</b></div>
  </section>
  <section className="rounded-2xl border border-stone-200 bg-white p-5">
    <div className="flex items-center justify-between gap-3"><div><p className="text-xs font-extrabold uppercase tracking-wider text-primary-700">Reviews</p><h2 className="mt-2 text-lg font-extrabold">A little reassurance</h2></div><span className="flex items-center gap-1 rounded-full bg-accent-50 px-3 py-1.5 text-sm font-extrabold"><Star size={15} fill="currentColor" className="text-accent-500" /> {p.rating}</span></div>
    <blockquote className="mt-4 border-t border-stone-100 pt-4"><p className="text-sm leading-6 text-ink-700">“{p.info} The team made it easy to plan the right care for my pet.”</p><footer className="mt-2 text-xs font-bold text-ink-500">Sample review · {p.city}</footer></blockquote>
  </section>
</div>
    </div>
    <form onSubmit={submit} className={`${card} space-y-4 lg:sticky lg:top-24`}><div><p className="text-xs font-extrabold uppercase tracking-wider text-primary-700">Make it official</p><h2 className="mt-1 text-xl font-extrabold">Book this service</h2><p className="mt-2 text-sm text-ink-500">Choose a pet and a time. We’ll take it from there.</p></div><div className="flex items-baseline justify-between border-y border-stone-100 py-3"><span className="text-sm text-ink-500">Starting from</span><span className="text-xl font-extrabold text-primary-700">{p.price} <small className="text-xs font-semibold">EGP</small></span></div>{pets.length ? <><label className="block text-xs font-bold">Your pet<span className="mt-2 flex items-center gap-3"><PetAvatar name={pets.find((pet) => pet.id === +f.pet)?.name} photo={pets.find((pet) => pet.id === +f.pet)?.photo} className="size-10" iconSize={12} /><select required aria-label="Choose your pet" className={input} value={f.pet} onChange={set("pet")}>{pets.map((pet) => <option key={pet.id} value={pet.id}>{pet.name}</option>)}</select></span></label><label className="block text-xs font-bold">Date<input required aria-label="Appointment date" type="date" className={`${input} mt-2`} value={f.date} onChange={set("date")} /></label><label className="block text-xs font-bold">Time<input required aria-label="Appointment time" type="time" className={`${input} mt-2`} value={f.time} onChange={set("time")} /></label><label className="block text-xs font-bold">Notes <span className="font-normal text-ink-500">(optional)</span><textarea aria-label="Notes" className={`${input} mt-2`} rows="3" placeholder="Anything the provider should know?" value={f.notes} onChange={set("notes")} /></label></> : <p className="rounded-xl bg-red-50 p-3 text-sm text-danger-600">Add a pet first from My Pets to book this service.</p>}<button disabled={!pets.length || saving} className={`${btn} w-full`}>{saving ? "Booking..." : <><CalendarDays size={17} /> Confirm booking</>}</button><p className="text-center text-xs text-ink-500">No payment is collected now.</p></form></div></div>;
}
