import { useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, Check, Minus, Plus, Search, ShoppingBag, ShoppingCart, Trash2 } from "lucide-react";
import { products } from "../data.js";
import { useApp } from "../store.jsx";
import { btn, btn2, card, input } from "../ui.js";
import Media from "../components/Media.jsx";
const cats = ["All", ...new Set(products.map((p) => p.cat))];
export function Store() {
  const { addToCart } = useApp();
  const [cat, setCat] = useState("All"); const [q, setQ] = useState(""); const [sort, setSort] = useState("featured"); const [notice, setNotice] = useState("");
  const list = products.filter((p) => (cat === "All" || p.cat === cat) && p.name.toLowerCase().includes(q.toLowerCase())).sort((a, b) => sort === "low" ? a.price - b.price : sort === "high" ? b.price - a.price : a.id - b.id);
  const addProduct = (product) => { addToCart(product); setNotice(`${product.name} added to your cart.`); window.setTimeout(() => setNotice(""), 2500); };
  return <div><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-wider text-primary-700">The PetCare shop</p><h1 className="mt-2 text-3xl font-extrabold">Good things for good pets</h1><p className="mt-2 text-sm text-ink-500">Everyday essentials, selected with care.</p></div><Link to="/cart" className={`${btn2} relative`}><ShoppingCart size={17} /> View cart</Link></div>
    <div className="mb-7 flex flex-col gap-4 rounded-2xl border border-stone-200 bg-white p-4 sm:flex-row sm:items-center"><label className="relative flex-1"><span className="sr-only">Search products</span><Search size={17} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-ink-500" /><input aria-label="Search products" className={`${input} pl-10`} placeholder="Search products" value={q} onChange={(e) => setQ(e.target.value)} /></label><div className="flex gap-2 overflow-x-auto pb-1 sm:pb-0">{cats.map((category) => <button key={category} type="button" aria-pressed={cat === category} onClick={() => setCat(category)} className={`shrink-0 rounded-full px-4 py-2 text-xs font-bold transition ${cat === category ? "bg-primary-700 text-white" : "bg-stone-100 text-ink-700 hover:bg-primary-50"}`}>{category}</button>)}</div><label className="sr-only" htmlFor="product-sort">Sort products</label><select id="product-sort" className={`${input} sm:w-44`} value={sort} onChange={(event) => setSort(event.target.value)}><option value="featured">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></div>
    {list.length ? <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">{list.map((product) => <article key={product.id} className={`${card} group overflow-hidden p-0 hover:-translate-y-1 hover:shadow-lg`}><div className="relative h-40 overflow-hidden sm:h-48"><Media src={product.image} alt={product.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><span className="absolute left-3 top-3 rounded-full bg-white/95 px-2.5 py-1 text-[10px] font-bold text-ink-700">{product.cat}</span></div><div className="p-4"><h2 className="min-h-10 text-sm font-extrabold leading-5">{product.name}</h2><p className="mt-2 font-bold text-primary-700">{product.price} EGP</p><button type="button" className={`${btn} mt-4 w-full px-3 text-xs sm:text-sm`} onClick={() => addProduct(product)}><Plus size={15} /> Add to cart</button></div></article>)}</div> : <div className={`${card} py-14 text-center`}><ShoppingBag size={27} className="mx-auto text-ink-500" /><h2 className="mt-4 font-extrabold">No products found</h2><p className="mt-1 text-sm text-ink-500">Try a different search or category.</p></div>}
    {notice && <div role="status" aria-live="polite" className="fixed bottom-20 right-4 z-50 flex items-center gap-3 rounded-xl bg-ink-900 px-4 py-3 text-sm font-semibold text-white shadow-xl lg:bottom-6"><Check size={18} className="text-accent-400" />{notice}</div>}</div>;
}
export function Cart() {
  const { cart, changeQty, setCart } = useApp();
  const [done, setDone] = useState(false);
  const [addr, setAddr] = useState(""); const [pay, setPay] = useState("Cash on delivery");
  const total = cart.reduce((s, i) => s + i.price * i.qty, 0);
  if (done) return <div className={`${card} mx-auto max-w-xl py-14 text-center`}><span className="mx-auto grid size-16 place-items-center rounded-full bg-primary-50 text-primary-700"><Check size={30} /></span><h1 className="mt-5 text-2xl font-extrabold">Order confirmed</h1><p className="mt-2 text-sm text-ink-500">Your order is on its way to checkout success.</p><Link to="/store" className={`${btn} mt-6`}>Continue shopping <ArrowRight size={16} /></Link></div>;
  if (!cart.length) return <div className={`${card} mx-auto max-w-xl py-14 text-center`}><span className="mx-auto grid size-16 place-items-center rounded-full bg-primary-50 text-primary-700"><ShoppingBag size={28} /></span><h1 className="mt-5 text-2xl font-extrabold">Your cart is waiting</h1><p className="mt-2 text-sm text-ink-500">Find something lovely for your pet in the shop.</p><Link className={`${btn} mt-6`} to="/store">Explore the store <ArrowRight size={16} /></Link></div>;
  return <div><div className="mb-8"><p className="text-xs font-extrabold uppercase tracking-wider text-primary-700">Almost yours</p><h1 className="mt-2 text-3xl font-extrabold">Your cart</h1></div><div className="grid items-start gap-6 lg:grid-cols-[1fr_360px]"><div className="space-y-3">{cart.map((item) => <article key={item.id} className={`${card} flex flex-wrap items-center gap-4 p-4 sm:flex-nowrap`}><Media src={item.image} alt={item.name} className="size-20 shrink-0 rounded-xl object-cover" /><div className="min-w-0 flex-1"><h2 className="truncate font-extrabold">{item.name}</h2><p className="mt-1 text-sm text-ink-500">{item.price} EGP each</p></div><div className="flex items-center gap-2"><button aria-label={`Remove one ${item.name}`} className={`${btn2} size-9 min-h-9 p-0`} onClick={() => changeQty(item.id, -1)}><Minus size={15} /></button><span className="w-6 text-center text-sm font-bold">{item.qty}</span><button aria-label={`Add one ${item.name}`} className={`${btn2} size-9 min-h-9 p-0`} onClick={() => changeQty(item.id, 1)}><Plus size={15} /></button></div><span className="w-24 text-right text-sm font-extrabold">{item.price * item.qty} EGP</span></article>)}</div>
    <form className={`${card} space-y-4 lg:sticky lg:top-24`} onSubmit={(e) => { e.preventDefault(); setCart([]); setDone(true); }}><div><p className="text-xs font-extrabold uppercase tracking-wider text-primary-700">Delivery details</p><h2 className="mt-1 text-xl font-extrabold">Checkout</h2></div><label className="block text-xs font-bold">Delivery address<input required className={`${input} mt-2`} placeholder="Street, building, city" value={addr} onChange={(e) => setAddr(e.target.value)} /></label><label className="block text-xs font-bold">Payment method<select className={`${input} mt-2`} value={pay} onChange={(e) => setPay(e.target.value)}><option>Cash on delivery</option><option>Credit card</option></select></label><div className="space-y-2 border-t border-stone-100 pt-4 text-sm"><div className="flex justify-between text-ink-500"><span>Subtotal</span><span>{total} EGP</span></div><div className="flex justify-between text-ink-500"><span>Delivery</span><span>Free</span></div><div className="flex justify-between border-t border-stone-100 pt-3 text-base font-extrabold"><span>Total</span><span>{total} EGP</span></div></div><button className={`${btn} w-full`}><ShoppingBag size={17} /> Place order</button><Link to="/store" className="block text-center text-xs font-bold text-primary-700">Continue shopping</Link></form></div></div>;
}
